import { IAttributes } from '../../../Base/Index';
import { Instance } from '../../../../Core/Index';

export interface GrnAttributes extends IAttributes {
    Id: number;
    GrnNumber: string;
    GrnDate: Date;
    GrnTypeId: number;
    GrnSubTypeId: number;
    GrnStatusId: number;
    PoStatusId: number;
    SubmissionStatusId: number;
    PurchaseOrderId: number;
    PoNumber: string;
    PoDate: Date;
    IsGeneralPoGrn: boolean;
    IsGeneralGrn: boolean;
    PurchaseReturnId: number;
    PrnNumber: string;
    PrnDate: Date;
    VendorMasterId: number;
    VendorName: string;
    StoreMasterId: number;
    StoreName: string;
    SubmittedBy: number;
    SubmittedDate: Date;
    InvReceivedBy: number;
    InvReceivedDate: Date;
    ReceivedBy: number;
    ReceivedDate: Date;
    ReceiverComments: string;
    InvRejectedBy: number;
    InvRejectedDate: Date;
    InvRejectedComments: string;
    InvoiceNumber: string;
    InvoiceDate: Date;
    DcNumber: string;
    DcDate: Date;
    GpNumber: string;
    GpDate: Date;
    TotalGrossAmount: number;
    GrnDiscount: number;
    TotalDiscountAmount: number;
    TotalDiscount1Amount: number;
    TotalDiscount2Amount: number;
    TotalGstAmount: number;
    TotalInGstAmount: number;
    TotalCGstAmount: number;
    TotalSGstAmount: number;
    TotalCreditAmount: number;
    ShippingCharges: number;
    OtherCharges: number;
    TransportCharges: number;
    OtherChargesGstId: number;
    OtherChargesGstPercentage: number;
    OtherChargesGstAmount: number;
    TransportChargesGstId: number;
    TransportChargesGstPercentage: number;
    TransportChargesGstAmount: number;
    RoundOff: number;
    Discount1: number;
    Discount2: number;
    TotalNetAmount: number;
    ReceivedAmount: number;
    TaxAmount: number;
    WriteOff: number;
    BalanceAmount: number;
    TotalInvoiceAmount: number;
    VendorFacilityMapId: number;
    FacilityId: number;
    OrganisationId: number;
    CancelReasonId: number;
    Comments: string;
    AuthorizedBy: number;
    AuthorizedDate: Date;
    AuthorizerComments: string;
    ApprovedBy: number;
    ApprovedDate: Date;
    ApproverComments: string;
    IsOpenGRN: boolean;
    IsCredit: boolean;
    IsConvertionQtyEdit: boolean;
    IsPaidFully: boolean;
    IsStockTransferred: boolean;
    IsConsignment: boolean;
    IsConsignmentPO: boolean;
    IsConsignmentDC: boolean;
    RemarkId: number;
    TallyApprovedStatusId: number;
    PaymentTermsId: number;
    PANNo: string;
    GSTNo: string;
    TANNo: string;
    Status: number;
    Rev: number;
    CreatedBy: number;
    CreatedAt: Date;
    UpdatedBy: number;
    UpdatedAt: Date;
}

export interface GrnInstance extends Instance<GrnAttributes> {
    // Im exposing every DB column as an instance field to so that tsc wont complain.
    // CreatedAt: Date;
    // UpdatedAt: Date;
    dataValues: GrnAttributes;
}
