import { IAttributes } from '../../../Base/Index';
import { Instance } from '../../../../Core/Index';

export interface PurchaseOrderAttributes extends IAttributes {
    PurchaseOrderId: number;
    PoNumber: string;
    PoDate: Date;
    PrNumber: string;
    PrDate: Date;
    VendorMasterId: number;
    VendorName: string;
    StoreMasterId: number;
    StoreName: string;
    DeliveryStoreMasterId: number;
    DeliveryStoreName: string;
    DeliveryDate: Date;
    IsOpenPO: boolean;
    CancelledBy: number;
    CancelledDate: Date;
    CancelledComments: string;
    IsGeneralPo: boolean;
    PoTypeId: number;
    PoSubTypeId: number;
    PoStatusId: number;
    VendorFacilityMapId: number;
    FacilityId: number;
    FromFacilityId: number;
    ToFacilityId: number;
    PatientId: number;
    PatientBillId: number;
    DcDate: Date;
    DcNumber: string;
    EncounterId: number;
    IsConsignment: boolean;
    OrganisationId: number;
    PaymentTermsId: number;
    PurchaseRequestId: number;
    RequestedBy: number;
    RequestedDate: Date;
    RequesterComments: string;
    AuthorizedBy: number;
    AuthorizedDate: Date;
    AuthorizerComments: string;
    ApprovedBy: number;
    ApprovedDate: Date;
    ApproverComments: string;
    AmendedBy: number;
    AmendedDate: Date;
    AmenderComments: string;
    TotalGrossAmount: number;
    TotalDiscountAmount: number;
    TotalDiscount1Amount: number;
    Discount1: number;
    Discount2: number;
    TotalDiscount2Amount: number;
    TotalGstAmount: number;
    RoundOff: number;
    TotalInGstAmount: number;
    TotalCGstAmount: number;
    TotalSGstAmount: number;
    OtherCharges: number;
    TotalNetAmount: number;
    TotalSaleAmount: number;
    TotalProfitAmount: number;
    ValidUntillDate: Date;
    LeviesandTaxes: string;
    DeliverySchedule: string;
    TermsofDispatch: string;
    TermsofPayment: string;
    AddressLine1: string;
    AddressLine2: string;
    AddressLine3: string;
    TransportCharges: number;
    OtherChargesGstId: number;
    OtherChargesGstPercentage: number;
    OtherChargesGstAmount: number;
    TransportChargesGstId: number;
    TransportChargesGstPercentage: number;
    TransportChargesGstAmount: number;
    Remarks: string;
    Comments: string;
    RemarkId: number;
    PANNo: string;
    GSTNo: string;
    TANNo: string;
    Attachment: string;
    Status: number;
    Rev: number;
    CreatedBy: number;
    CreatedAt: Date;
    UpdatedBy: number;
    UpdatedAt: Date;
}

export interface PurchaseOrderInstance extends Instance<PurchaseOrderAttributes> {
    // Im exposing every DB column as an instance field to so that tsc wont complain.
    // CreatedAt: Date;
    // UpdatedAt: Date;
    dataValues: PurchaseOrderAttributes;
}
