import { IAttributes } from '../../../Base/Index';
import { Instance } from '../../../../Core/Index';

export interface PatientReturnDetailsAttributes extends IAttributes {
    Id: number;
    PatientBillDetailId: number;
    PatientBillId: number;
    PatientReturnId: number;
    ReturnDateTime: Date;
    ServiceId: number;
    ServiceCode: string;
    ServiceName: string;
    ServiceTypeId: number;
    ServiceGroupId: number;
    ServiceCategoryId: number;
    MasterItemId: number;
    MasterTypeId: number;
    MasterName: string;
    DepartmentId: number;
    StoreMasterId: number;
    ItemMasterId: number;
    ItemCode: string;
    ItemName: string;
    GenericName: string;
    RackId: number;
    RackName: string;
    Shelf: string;
    Tray: string;
    IsPrescribed: boolean;
    ScheduleTypeId: number;
    ScheduleTypeDescription: string;
    BilledQuantity: number;
    ReturnQuantity: number;
    StockItemId: number;
    StockSerialItemId: number;
    BatchId: string;
    ExpiryDate: Date;
    Rate: number;
    ReturnedQuantity: number;
    SoldQuantity: number;
    Amount: number;
    GrossAmount: number;
    GrossGSTAmount: number;
    DiscountModeId: number;
    DiscountPercentage: number;
    UnitDiscountAmount: number;
    DiscountAmount: number;
    DoctorDiscountAmount: number;
    EducationCess: number;
    GSTAmount: number;
    UnitGSTAmount: number;
    NetAmountBeforeGST: number;
    NetAmount: number;
    InsNetAmount: number;
    PatNetAmount: number;
    FreeNetAmount: number;
    GSTId: number;
    GSTPercentage: number;
    GSTCode: string;
    InGstId: number;
    InGstPercentage: number;
    UnitInGstAmount: number;
    InGstAmount: number;
    CGstId: number;
    CGstPercentage: number;
    UnitCGstAmount: number;
    CGstAmount: number;
    SGstId: number;
    SGstPercentage: number;
    UnitSGstAmount: number;
    SGstAmount: number;
    DoctorId: number;
    DoctorName: string;
    IsGstDoctor: boolean;
    Comments: string;
    Status: number;
    Rev: number;
    CreatedBy: number;
    CreatedAt: Date;
    UpdatedBy: number;
    UpdatedAt: Date;
}

export interface PatientReturnDetailsInstance extends Instance<PatientReturnDetailsAttributes> {
    // I'm exposing every DB column as an instance field to so that tsc won't complain.
    // CreatedAt: Date;
    // UpdatedAt: Date;
    dataValues: PatientReturnDetailsAttributes;
}
