import { Router, GetRouter } from '../../../Core/Index';
import PatientAllergy from './PatientAllergyRoute';
import FamilyCondition from './FamilyConditionRoute';
import FamilySocialHistory from './FamilySocialHistoryRoute';
import PatientCondition from './PatientConditionRoute';
import PatientImmunization from './PatientImmunizationRoute';
import PatientMedication from './PatientMedicationRoute';
import PatientProcedure from './PatientProcedureRoute';
import PatientSocialHistory from './PatientSocialHistoryRoute';
import PatientVital from './PatientVitalRoute';
import Prescription from './PrescriptionRoute';
import PrescriptionDetail from './PrescriptionDetailRoute';
import PatientSurgical from './PatientSurgicalRoute';
import PatientOrder from './PatientOrderRoute';
import PatientOrderDetail from './PatientOrderDetailRoute';
import ClinicalDocument from './ClinicalDocumentRoute';
import PatientDiagnosis from './PatientDiagnosisRoute';
import PatientIntakeOutput from './PatientIntakeOutputRoute';
import PatientFeedback from './PatientFeedbackRoute';
import PatientFeedbackDetails from './PatientFeedbackDetailsRoute';
import PatientDietPlan from './PatientDietPlanRoute';
import PatientDietPlanLog from './PatientDietPlanLogRoute';
import PatientDietNbm from './PatientDietNbmRoute';
import PatientDietOrder from './PatientDietOrderRoute';
import PatientDietOrderDetail from './PatientDietOrderDetailRoute';
import NewBornDetail from './NewBornDetailRoute';
import PatientLabourDetail from './PatientLabourDetailRoute';
import DailyNote from './DailyNoteRoute';
import PatientAnnotation from './PatientAnnotationRoute';
import Consultation from './ConsultationRoute';
import PastLabResult from './PastLabResultRoute';
import PastLabResultDetail from './PastLabResultDetailRoute';
import CategorySectionEntry from './CategorySectionEntryRoute';
import PatientImmunizationSchedule from './PatientImmunizationScheduleRoute';
import PatientEmar from './PatientEmarRoute';
import PatientEmarDetails from './PatientEmarDetailsRoute';
import PatientChiefComplaint from './PatientChiefComplaintRoute';
import PatientVentilatorChart from './PatientVentilatorChartRoute';
import PatientMonitorChart from './PatientMonitorChartRoute';
import PatientABGChart from './PatientABGChartRoute';
import PatientBPChart from './PatientBPChartRoute';
import PatientDiabetesChart from './PatientDiabetesChartRoute';
import PatientDialysisChart from './PatientDialysisChartRoute';
import PatientEMRDashboard from './PatientEMRDashboardRoute';
import PatientRheumatology from './PatientRheumatologyRoute';
import IntakeOutputChart from './IntakeOutputChartRoute';
import LensPrescription from './LensPrescriptionRoute';
import PreOperativeChecklist from './PreOperativeChecklistRoute';
import PreOperativeChecklistDetails from './PreOperativeChecklistDetailsRoute';
import BloodRequest from './BloodRequestRoute';
import ShoulderAssessment from './ShoulderAssessmentRoute';
import PatientGeneralHistory from './PatientGeneralHistoryRoute';
import PatientComplaints from './PatientComplaintsRoute';
import PastOcularHistory from './PastOcularHistoryRoute';
import PatientExaminationSystem from './PatientExaminationSystemRoute';
import PatientSurgeryAdvice from './PatientSurgeryAdviceRoute';
import PatientInjectionAdvice from './PatientInjectionAdviceRoute';
import PatientLaserAdvice from './PatientLaserAdviceRouter';
import PatientToothChart from './PatientToothChartRoute';
import PatientDischargeMedication from './PatientDischargeMedicationRoute';
import PatientAdviceMedication from './PatientAdviceMedicationRoute';
import PatientTransfer from './PatientTransferRoute';
import ProcedureOrder from './ProcedureOrderRoute';
import ProcedureOrderDetail from './ProcedureOrderDetailRoute';
import PatientClinicalNotes from './PatientClinicalNotesRoute';
import TreatementModality from './TreatementModalityRoute';
import PhysiotheraphyTreatement from './PhysiotheraphyTreatementRoute';
import PositionBpChart from './PositionBpChartRoute';
import CdChart from './CdChartRoute';
import Emar from './EmarRoute';
import PatientFeedbackDashboard from './PatientFeedbackDashboardRoute';
import PrescriptionPad from './PrescriptionPadRoute';
import RevenueTarget from './RevenueTargetRoute';
import PatientNotifiableDisease from './PatientNotifiableDiseaseRoute';
import TreatmentPlan from './TreatmentPlanRoute';
import TreatmentPlanDetail from './TreatmentPlanDetailRoute';
import OrderFollowup from './OrderFollowupRoute';
import TreatmentPlanFollowup from './TreatmentPlanFollowupRoute';
import AdverseDrugReaction from './AdverseDrugReactionRoute';
import ExtravasationProforma from './ExtravasationProformaRoute';
import IncidentReporting from './IncidentReportingRoute';
import Document from './DocumentRoute';

let router: Router = GetRouter();
router.use('/PatientAllergy', PatientAllergy);
router.use('/FamilyCondition', FamilyCondition);
router.use('/FamilySocialHistory', FamilySocialHistory);
router.use('/PatientCondition', PatientCondition);
router.use('/PatientImmunization', PatientImmunization);
router.use('/PatientMedication', PatientMedication);
router.use('/PatientProcedure', PatientProcedure);
router.use('/PatientSocialHistory', PatientSocialHistory);
router.use('/PatientVital', PatientVital);
router.use('/Prescription', Prescription);
router.use('/PrescriptionDetail', PrescriptionDetail);
router.use('/PatientSurgical', PatientSurgical);
router.use('/PatientOrder', PatientOrder);
router.use('/PatientOrderDetail', PatientOrderDetail);
router.use('/ClinicalDocument', ClinicalDocument);
router.use('/PatientDiagnosis', PatientDiagnosis);
router.use('/PatientIntakeOutput', PatientIntakeOutput);
router.use('/PatientFeedback', PatientFeedback);
router.use('/PatientFeedbackDetails', PatientFeedbackDetails);
router.use('/PatientDietPlan', PatientDietPlan);
router.use('/PatientDietPlanLog', PatientDietPlanLog);
router.use('/PatientDietNbm', PatientDietNbm);
router.use('/PatientDietOrder', PatientDietOrder);
router.use('/PatientDietOrderDetail', PatientDietOrderDetail);
router.use('/NewBornDetail', NewBornDetail);
router.use('/PatientLabourDetail', PatientLabourDetail);
router.use('/DailyNote', DailyNote);
router.use('/PatientAnnotation', PatientAnnotation);
router.use('/Consultation', Consultation);
router.use('/PastLabResult', PastLabResult);
router.use('/PastLabResultDetail', PastLabResultDetail);
router.use('/CategorySectionEntry', CategorySectionEntry);
router.use('/PatientImmunizationSchedule', PatientImmunizationSchedule);
router.use('/PatientEmar', PatientEmar);
router.use('/PatientEmarDetails', PatientEmarDetails);
router.use('/PatientChiefComplaint', PatientChiefComplaint);
router.use('/PatientVentilatorChart', PatientVentilatorChart);
router.use('/PatientMonitorChart', PatientMonitorChart);
router.use('/PatientABGChart', PatientABGChart);
router.use('/PatientBPChart', PatientBPChart);
router.use('/PatientDiabetesChart', PatientDiabetesChart);
router.use('/PatientDialysisChart', PatientDialysisChart);
router.use('/PatientEMRDashboard', PatientEMRDashboard);
router.use('/PatientRheumatology', PatientRheumatology);
router.use('/IntakeOutputChart', IntakeOutputChart);
router.use('/LensPrescription', LensPrescription);
router.use('/PreOperativeChecklist', PreOperativeChecklist);
router.use('/PreOperativeChecklistDetails', PreOperativeChecklistDetails);
router.use('/BloodRequest', BloodRequest);
router.use('/ShoulderAssessment', ShoulderAssessment);
router.use('/PatientGeneralHistory', PatientGeneralHistory);
router.use('/PatientComplaints', PatientComplaints);
router.use('/PastOcularHistory', PastOcularHistory);
router.use('/PatientExaminationSystem', PatientExaminationSystem);
router.use('/PatientSurgeryAdvice', PatientSurgeryAdvice);
router.use('/PatientSurgeryAdvice', PatientSurgeryAdvice);
router.use('/PatientInjectionAdvice', PatientInjectionAdvice);
router.use('/PatientLaserAdvice', PatientLaserAdvice);
router.use('/PatientToothChart', PatientToothChart);
router.use('/PatientDischargeMedication', PatientDischargeMedication);
router.use('/PatientAdviceMedication', PatientAdviceMedication);
router.use('/PatientTransfer', PatientTransfer);
router.use('/ProcedureOrder', ProcedureOrder);
router.use('/ProcedureOrderDetail', ProcedureOrderDetail);
router.use('/PatientClinicalNotes', PatientClinicalNotes);
router.use('/TreatementModality', TreatementModality);
router.use('/PhysiotheraphyTreatement', PhysiotheraphyTreatement);
router.use('/Emar', Emar);
router.use('/PositionBpChart', PositionBpChart);
router.use('/CdChart', CdChart);
router.use('/PatientFeedbackDashboard', PatientFeedbackDashboard);
router.use('/PrescriptionPad', PrescriptionPad);
router.use('/RevenueTarget', RevenueTarget);
router.use('/PatientNotifiableDisease', PatientNotifiableDisease);
router.use('/TreatmentPlan', TreatmentPlan);
router.use('/TreatmentPlanDetail', TreatmentPlanDetail);
router.use('/OrderFollowup', OrderFollowup);
router.use('/TreatmentPlanFollowup', TreatmentPlanFollowup);
router.use('/AdverseDrugReaction', AdverseDrugReaction);
router.use('/ExtravasationProforma', ExtravasationProforma);
router.use('/IncidentReporting', IncidentReporting);
router.use('/Document', Document);
export default router;
