import { IAttributes } from '../../../Base/Index';
import { Instance } from '../../../../Core/Index';

export interface PatientLabourDetailAttributes extends IAttributes {
    Id: number;
    PatientId: number;
    EncounterId: number;
    GenderId: number;
    FacilityId: number;
    OrganizationId: number;
    LMPDate: Date;
    EDD: Date;
    GAWeeks: string;
    GADays: string;
    GAById: number;
    ScrubNurseId: number;
    AnesthesiologistId: number;
    PastDelivery: string;
    PastAndPresentHistory: number;
    Gravida: string;
    Para: string;
    FullTerm: string;
    Premature: string;
    Abortion: string;
    Living: string;
    StillBirth: string;
    NumberOfBirthChild: string;
    MembraneRupturedId: number;
    AmnoticFluidId: number;
    MembraneRupturedDateTime: Date;
    OnSetOfLabourDateTime: Date;
    DilationDateTime: Date;
    BirthOfChildDateTime: Date;
    BirthOfPlacentaDateTIme: Date;
    StageDilationHrs: string;
    StageDilationMin: string;
    StageBirthOfChildHrs: string;
    StageBirthOfChildMin: string;
    BirthOfPlacentaHrs: string;
    BirthOfPlacentaMin: string;
    DurationOfLabourHrs: string;
    DurationOfLabourMin: string;
    ModeOfDeliveryId: number;
    Complications: string;
    PresentationId: number;
    IndicationId: number;
    GrossId: number;
    Episiotomy: number;
    Laceration: number;
    RespirationId10min: number;
    FoetalHeartRate: string;
    Contraction: string;
    AnesthesiaId: number;
    AnesthesiaTime: Date;
    PlacentaAndMembraneId: number;
    TribandNumber1: string;
    TribandNumber2: string;
    TribandNumber3: string;
    CordLength: string;
    PlacentaWeight: string;
    GrossAppearanceId: number;
    PostPartumConditionId: number;
    EBL: string;
    MedicationId: number;
    DoctorId: number;
    AnesthesiologistName: string;
    ScrubNurseName: string;
    AssistantId: number;
    Remarks: string;
    LabourId: number;
    EpisiotomyId: number;
    LacerationId: number;
    Medication: string;
    LabourStatusId: number;
    SM: string;
    MidWife: string;
    Rev: number;
    CreatedBy: number;
    CreatedAt: Date;
    UpdatedBy: number;
    UpdatedAt: Date;
}

export interface PatientLabourDetailInstance extends Instance<PatientLabourDetailAttributes> {
    // I'm exposing every DB column as an instance field to so that tsc won't complain.
    // CreatedAt: Date;
    // UpdatedAt: Date;
    dataValues: PatientLabourDetailAttributes;
}
