import * as SequelizeStatic from 'sequelize';
import { DataTypes, Sequelize } from 'sequelize';
import * as i from './Interface/Index';

export default function (sequelize: Sequelize, DataTypes: DataTypes):
    SequelizeStatic.Model<i.PharmacyModifyPatBillDetailsInstance, i.PharmacyModifyPatBillDetailsAttributes> {
    let PharmacyModifyPatBillDetails =
        sequelize.define<i.PharmacyModifyPatBillDetailsInstance, i.PharmacyModifyPatBillDetailsAttributes>('PharmacyModifyPatBillDetails', {
            Id: { type: DataTypes.BIGINT, field: 'PatientBillDetailId', primaryKey: true },
            PatientBillId: { type: DataTypes.BIGINT, field: 'PatientBillId' },
            BillDateTime: { type: DataTypes.DATE, field: 'BillDateTime' },
            ServiceId: { type: DataTypes.BIGINT, field: 'ServiceId' },
            ServiceName: { type: DataTypes.STRING, field: 'ServiceName' },
            ServiceCode: { type: DataTypes.STRING, field: 'ServiceCode' },
            ServiceTypeId: { type: DataTypes.BIGINT, field: 'ServiceTypeId' },
            ServiceGroupId: { type: DataTypes.BIGINT, field: 'ServiceGroupId' },
            ServiceCategoryId: { type: DataTypes.BIGINT, field: 'ServiceCategoryId' },
            MasterTypeId: { type: DataTypes.BIGINT, field: 'MasterTypeId' },
            MasterItemId: { type: DataTypes.BIGINT, field: 'MasterItemId' },
            EncounterId: { type: DataTypes.BIGINT, field: 'EncounterId' },
            PatientBillStatusId: { type: DataTypes.BIGINT, field: 'PatientBillStatusId' },
            MasterName: { type: DataTypes.STRING, field: 'MasterName' },
            Quantity: { type: DataTypes.INTEGER, field: 'Quantity' },
            IsAutoBillModified: { type: DataTypes.BOOLEAN, field: 'IsAutoBillModified' },
            ReturnedQuantity: { type: DataTypes.INTEGER, field: 'ReturnedQuantity' },
            StockItemId: { type: DataTypes.BIGINT, field: 'StockItemId' },
            StockSerialItemId: { type: DataTypes.BIGINT, field: 'StockSerialItemId' },
            BatchId: { type: DataTypes.STRING, field: 'BatchId' },
            ExpiryDate: { type: DataTypes.DATE, field: 'ExpiryDate' },
            IsMultiUse: { type: DataTypes.BOOLEAN, field: 'IsMultiUse' },
            NoOfTransactions: { type: DataTypes.STRING, field: 'NoOfTransactions' },
            TotalTransactions: { type: DataTypes.STRING, field: 'TotalTransactions' },
            ConsumedTransactions: { type: DataTypes.STRING, field: 'ConsumedTransactions' },
            PendingTransactions: { type: DataTypes.STRING, field: 'PendingTransactions' },
            Rate: { type: DataTypes.DECIMAL, field: 'Rate' },
            UnitPrice: { type: DataTypes.DECIMAL, field: 'UnitPrice' },
            Amount: { type: DataTypes.DECIMAL, field: 'Amount' },
            GrossAmount: { type: DataTypes.DECIMAL, field: 'GrossAmount' },
            GrossGSTAmount: { type: DataTypes.DECIMAL, field: 'GrossGSTAmount' },
            DiscountPercentage: { type: DataTypes.DECIMAL, field: 'DiscountPercentage' },
            UnitDiscountAmount: { type: DataTypes.DECIMAL, field: 'UnitDiscountAmount' },
            DiscountAmount: { type: DataTypes.DECIMAL, field: 'DiscountAmount' },
            UnitProportionateDiscount: { type: DataTypes.DECIMAL, field: 'UnitProportionateDiscount' },
            ProportionateDiscount: { type: DataTypes.DECIMAL, field: 'ProportionateDiscount' },
            DoctorDiscountAmount: { type: DataTypes.DECIMAL, field: 'DoctorDiscountAmount' },
            EducationCess: { type: DataTypes.DECIMAL, field: 'EducationCess' },
            UnitGSTAmount: { type: DataTypes.DECIMAL, field: 'UnitGSTAmount' },
            GSTAmount: { type: DataTypes.DECIMAL, field: 'GSTAmount' },
            NetAmountBeforeGST: { type: DataTypes.DECIMAL, field: 'NetAmountBeforeGST' },
            NetAmount: { type: DataTypes.DECIMAL, field: 'NetAmount' },
            ReceivedAmount: { type: DataTypes.DECIMAL, field: 'ReceivedAmount' },
            ReturnedAmount: { type: DataTypes.DECIMAL, field: 'ReturnedAmount' },
            GSTId: { type: DataTypes.DECIMAL, field: 'GSTId' },
            GSTPercentage: { type: DataTypes.DECIMAL, field: 'GSTPercentage' },
            TaxCode: { type: DataTypes.STRING, field: 'TaxCode' },
            InGstId: { type: DataTypes.BIGINT, field: 'InGstId' },
            InGstPercentage: { type: DataTypes.DECIMAL, field: 'InGstPercentage' },
            UnitInGstAmount: { type: DataTypes.DECIMAL, field: 'UnitInGstAmount' },
            InGstAmount: { type: DataTypes.DECIMAL, field: 'InGstAmount' },
            CGstId: { type: DataTypes.BIGINT, field: 'CGstId' },
            CGstPercentage: { type: DataTypes.DECIMAL, field: 'CGstPercentage' },
            UnitCGstAmount: { type: DataTypes.DECIMAL, field: 'UnitCGstAmount' },
            CGstAmount: { type: DataTypes.DECIMAL, field: 'CGstAmount' },
            SGstId: { type: DataTypes.BIGINT, field: 'SGstId' },
            SGstPercentage: { type: DataTypes.DECIMAL, field: 'SGstPercentage' },
            UnitSGstAmount: { type: DataTypes.DECIMAL, field: 'UnitSGstAmount' },
            SGstAmount: { type: DataTypes.DECIMAL, field: 'SGstAmount' },
            DoctorId: { type: DataTypes.BIGINT, field: 'DoctorId' },
            DoctorName: { type: DataTypes.STRING, field: 'DoctorName' },
            IsPackageItem: { type: DataTypes.BOOLEAN, field: 'IsPackageItem' },
            PackageId: { type: DataTypes.BIGINT, field: 'PackageId' },
            PackageName: { type: DataTypes.STRING, field: 'PackageName' },
            OrderId: { type: DataTypes.BIGINT, field: 'OrderId' },
            OrderDetailId: { type: DataTypes.BIGINT, field: 'OrderDetailId' },
            OrderTypeId: { type: DataTypes.BIGINT, field: 'OrderTypeId' },
            OrderStatusId: { type: DataTypes.BIGINT, field: 'OrderStatusId' },
            OrderDateTime: { type: DataTypes.DATE, field: 'OrderDateTime' },
            OTRegisterId: { type: DataTypes.BIGINT, field: 'OTRegisterId' },
            ProcedureId: { type: DataTypes.BIGINT, field: 'ProcedureId' },
            PrescriptionId: { type: DataTypes.BIGINT, field: 'PrescriptionId' },
            PrescriptionDetailId: { type: DataTypes.BIGINT, field: 'PrescriptionDetailId' },
            PrescriptionTypeId: { type: DataTypes.BIGINT, field: 'PrescriptionTypeId' },
            PrescriptionStatusId: { type: DataTypes.BIGINT, field: 'PrescriptionStatusId' },
            PrescriptionDate: { type: DataTypes.DATE, field: 'PrescriptionDate' },
            ServiceRateCategoryId: { type: DataTypes.BIGINT, field: 'ServiceRateCategoryId' },
            ServiceRateCategoryName: { type: DataTypes.STRING, field: 'ServiceRateCategoryName' },
            IsModified: { type: DataTypes.BOOLEAN, field: 'IsModified' },
            IsSupplementary: { type: DataTypes.BOOLEAN, field: 'IsSupplementary' },
            IsBillable: { type: DataTypes.BOOLEAN, field: 'IsBillable' },
            IsPharmacyCredit: { type: DataTypes.INTEGER, field: 'IsPharmacyCredit' },
            IsPharmacySale: { type: DataTypes.BOOLEAN, field: 'IsPharmacySale' },
            PharmacySaleTypeId: { type: DataTypes.BIGINT, field: 'PharmacySaleTypeId' },
            IsPharmacyReturn: { type: DataTypes.BOOLEAN, field: 'IsPharmacyReturn' },
            PharmacyReturnTypeId: { type: DataTypes.BIGINT, field: 'PharmacyReturnTypeId' },
            IsDoctorDiscount: { type: DataTypes.BOOLEAN, field: 'IsDoctorDiscount' },
            IsGstDoctor: { type: DataTypes.BOOLEAN, field: 'IsGstDoctor' },
            StartDateTime: { type: DataTypes.DATE, field: 'StartDateTime' },
            EndDateTime: { type: DataTypes.DATE, field: 'EndDateTime' },
            AllowStaffDiscount: { type: DataTypes.BOOLEAN, field: 'AllowStaffDiscount' },
            DiscountTypeId: { type: DataTypes.BIGINT, field: 'DiscountTypeId' },
            DiscountModeId: { type: DataTypes.BIGINT, field: 'DiscountModeId' },
            Discount: { type: DataTypes.DECIMAL, field: 'Discount' },
            DiscountAuthorizedBy: { type: DataTypes.INTEGER, field: 'DiscountAuthorizedBy' },
            DoctorShare: { type: DataTypes.DECIMAL, field: 'DoctorShare' },
            DoctorShareActual: { type: DataTypes.DECIMAL, field: 'DoctorShareActual' },
            DoctorShareDisc: { type: DataTypes.DECIMAL, field: 'DoctorShareDisc' },
            ReferalShare: { type: DataTypes.DECIMAL, field: 'ReferalShare' },
            CancelReason: { type: DataTypes.STRING, field: 'CancelReason' },
            CancelledBy: { type: DataTypes.BIGINT, field: 'CancelledBy' },
            OpticalItemMasterId: { type: DataTypes.BIGINT, field: 'OpticalItemMasterId' },
            ItemMasterId: { type: DataTypes.BIGINT, field: 'ItemMasterId' },
            ItemCode: { type: DataTypes.STRING, field: 'ItemCode' },
            ItemName: { type: DataTypes.STRING, field: 'ItemName' },
            ScheduleTypeId: { type: DataTypes.BIGINT, field: 'ScheduleTypeId' },
            ScheduleTypeDescription: { type: DataTypes.STRING, field: 'ScheduleTypeDescription' },
            GenericId: { type: DataTypes.BIGINT, field: 'GenericId' },
            GenericName: { type: DataTypes.STRING, field: 'GenericName' },
            IsNonClaimable: { type: DataTypes.BOOLEAN, field: 'IsNonClaimable' },
            RackId: { type: DataTypes.BIGINT, field: 'RackId' },
            RackName: { type: DataTypes.STRING, field: 'RackName' },
            Shelf: { type: DataTypes.STRING, field: 'Shelf' },
            Tray: { type: DataTypes.STRING, field: 'Tray' },
            IsPrescribed: { type: DataTypes.BOOLEAN, field: 'IsPrescribed' },
            ManufacturerId: { type: DataTypes.BIGINT, field: 'ManufacturerId' },
            ManufacturerName: { type: DataTypes.STRING, field: 'ManufacturerName' },
            StoreMasterId: { type: DataTypes.BIGINT, field: 'StoreMasterId' },
            IsInvoicedDoctorShare: { type: DataTypes.INTEGER, field: 'IsInvoicedDoctorShare' },
            IsNightCharge: { type: DataTypes.BOOLEAN, field: 'IsNightCharge' },
            Comments: { type: DataTypes.STRING, field: 'Comments' },
            Status: { type: DataTypes.INTEGER, field: 'Status' },
            Rev: { type: DataTypes.INTEGER, field: 'Rev' },
            CreatedBy: { type: DataTypes.INTEGER, field: 'CreatedBy' },
            CreatedAt: { type: DataTypes.DATE, field: 'CreatedAt' },
            UpdatedBy: { type: DataTypes.INTEGER, field: 'UpdatedBy' },
            UpdatedAt: { type: DataTypes.DATE, field: 'UpdatedAt' },
            DepartmentId: { type: DataTypes.BIGINT, field: 'DepartmentId' },
            CNAmount: { type: DataTypes.DECIMAL, field: 'CNAmount' },
            AliasId: { type: DataTypes.STRING, field: 'AliasId' },
            AliasName: { type: DataTypes.STRING, field: 'AliasName' },
            IPBillDetailId: { type: DataTypes.BIGINT, field: 'IPBillDetailId' },
            IsInclusionItem: { type: DataTypes.BOOLEAN, field: 'IsInclusionItem' },
            IsExclusionItem: { type: DataTypes.BOOLEAN, field: 'IsExclusionItem' },
            IsExecutableProcedure: { type: DataTypes.BOOLEAN, field: 'IsExecutableProcedure' },
            Remarks: { type: DataTypes.STRING, field: 'Remarks' },
            DoctorClassId: { type: DataTypes.BIGINT, field: 'DoctorClassId' },
            EligiblePercentage: { type: DataTypes.DECIMAL, field: 'EligiblePercentage' },
            SharePercentage: { type: DataTypes.DECIMAL, field: 'SharePercentage' },
            ShareAmount: { type: DataTypes.DECIMAL, field: 'ShareAmount' },
            DrShareTaxId: { type: DataTypes.BIGINT, field: 'DrShareTaxId' },
            DrTaxPercentage: { type: DataTypes.DECIMAL, field: 'DrTaxPercentage' },
            DrTaxAmount: { type: DataTypes.DECIMAL, field: 'DrTaxAmount' },
            FreeNetAmount: { type: DataTypes.DECIMAL, field: 'FreeNetAmount' },
            PackageMasterServiceId: { type: DataTypes.DECIMAL, field: 'PackageMasterServiceId' },
            IsExecutingService: { type: DataTypes.BOOLEAN, field: 'IsExecutingService' },
        },
            {
                indexes: [],
                timestamps: true,
                tableName: 'hims_pharmacymodifypatbilldetails',
                createdAt: 'CreatedAt',
                updatedAt: 'UpdatedAt',
                freezeTableName: true,
                defaultScope: {
                    where: {
                        Status: 1
                    }
                }
            });

    (PharmacyModifyPatBillDetails as any).associate = function (models: Models) {
        PharmacyModifyPatBillDetails.belongsTo(models.Department);
        PharmacyModifyPatBillDetails.belongsTo(models.ServiceItem, { foreignKey: 'ServiceId' });
        PharmacyModifyPatBillDetails.belongsTo(models.ServiceCategory, { foreignKey: 'ServiceCategoryId' });
        PharmacyModifyPatBillDetails.belongsTo(models.User, { as: 'CreatedUser', foreignKey: 'CreatedBy' });
        PharmacyModifyPatBillDetails.belongsTo(models.User, { foreignKey: 'DoctorId' });
        PharmacyModifyPatBillDetails.belongsTo(models.StoreMaster, { foreignKey: 'StoreMasterId' });
        PharmacyModifyPatBillDetails.belongsTo(models.ItemMaster, { foreignKey: 'ItemMasterId' });
        PharmacyModifyPatBillDetails.belongsTo(models.OpticalItemMaster, { foreignKey: 'OpticalItemMasterId' });
        PharmacyModifyPatBillDetails.belongsTo(models.PharmacyModifyPatBills, { foreignKey: 'PatientBillId' });
        PharmacyModifyPatBillDetails.belongsTo(models.Encounter);
        PharmacyModifyPatBillDetails.belongsTo(models.ReferenceValue, { as: 'PatientBillStatus', targetKey: 'ReferenceValueCodeId' });
        PharmacyModifyPatBillDetails.belongsTo(models.OrderStatus);
    };
    return PharmacyModifyPatBillDetails;
}
