import { Router, GetRouter } from '../../../Core/Index';
import VirtualCategory from './VirtualCategoryRoute';
import VirtualSubCategory from './VirtualSubCategoryRoute';
import VirtualOrder from './VirtualOrderRoute';
import VirtualOrderDetail from './VirtualOrderDetailRoute';
import VirtualBill from './VirtualBillRoute';
import VirtualBillDetail from './VirtualBillDetailRoute';
import VirtualConference from './VirtualConferenceRoute';
import VirtualConferenceSession from './VirtualConferenceSessionRoute';
import VirtualConferenceParticipant from './VirtualConferenceParticipantRoute';
import VirtualConferenceSessionUser from './VirtualConferenceSessionUserRoute';
import VirtualPayment from './VirtualPaymentRoute';
import BannerContent from './BannerContentRoute';
import SuccessStory from './SuccessStoryRoute';
import VirtualMedicineOrder from './VirtualMedicineOrderRoute';
import VirtualMedicineOrderDetail from './VirtualMedicineOrderDetailRoute';

let router: Router = GetRouter();
router.use('/VirtualCategory', VirtualCategory);
router.use('/VirtualSubCategory', VirtualSubCategory);
router.use('/VirtualOrder', VirtualOrder);
router.use('/VirtualOrderDetail', VirtualOrderDetail);
router.use('/VirtualBill', VirtualBill);
router.use('/VirtualBillDetail', VirtualBillDetail);
router.use('/VirtualConference', VirtualConference);
router.use('/VirtualConferenceSession', VirtualConferenceSession);
router.use('/VirtualConferenceParticipant', VirtualConferenceParticipant);
router.use('/VirtualConferenceSessionUser', VirtualConferenceSessionUser);
router.use('/VirtualPayment', VirtualPayment);
router.use('/BannerContent', BannerContent);
router.use('/SuccessStory', SuccessStory);
router.use('/VirtualMedicineOrder', VirtualMedicineOrder);
router.use('/VirtualMedicineOrderDetail', VirtualMedicineOrderDetail);
export default router;
