export * from './OtRequestInterface';
export * from './SurgeryEntryInterface';
export * from './OtPatientEquipmentsInterface';
export * from './OtNotesInterface';
export * from './OtDocumentInterface';
export * from './OtScheduleInterface';
export * from './SurgeryRoomMasterInterface';
export * from './OtScheduleDetailsInterface';
export * from './SurgeryEntryDetailsInterface';
