import { IAttributes } from '../../../Base/Index';
import { Instance } from '../../../../Core/Index';

export interface PatientMergeAttributes extends IAttributes {
    Id: number;
    TrasactionId: number;
    PatientId: number;
    TitleId: number;
    FirstName: string;
    MiddleName: string;
    LastName: string;
    Age: number;
    DOB: Date;
    MaritalStatusId: number;
    GuardianTypeId: number;
    GuardianName: string;
    ReligionId: number;
    PreferredLanguageId: number;
    Qualification: string;
    NationalityId: number;
    NationalityIdentifier: string;
    PasspostNumber: string;
    VisaTypeId: number;
    VisaNumber: string;
    VisaExpiry: Date;
    IsVip: boolean;
    IsRecipient: boolean;
    IsCouple: boolean;
    PatientAssociate: string;
    VipTypeId: number;
    PatientTypeId: number;
    OccupationId: number;
    BloodGroupId: number;
    ReferTypeId: number;
    ReferrerId: number;
    AddressLine1: string;
    AddressLine2: string;
    Pincode: string;
    Area: string;
    City: string;
    State: string;
    Country: string;
    LandLine: string;
    Mobile: string;
    Email: string;
    IsSmsCommunicationPreference: boolean;
    IsEmailCommunicationPreference: boolean;
    IsMRDRequest: boolean;
    GenderId: number;
    MRN: string;
    PinCodeId: number;
    CityId: number;
    StateId: number;
    CountryId: number;
    AliasName: string;
    GuarantorId: number;
    RegisteredDate: Date;
    PatientStatusId: number;
    MRNTypeId: number;
    PhotoPath: string;
    IsBirthDateApproximate: boolean;
    DeathDate: Date;
    DeathTypeId: number;
    DeathPlaceId: number;
    IsDeathConfirmed: boolean;
    DeathConfirmedBy: number;
    DeathComents: string;
    DeathUpdatedBy: number;
    DeathUpdatedDate: Date;
    DeathApprovedBy: number;
    FacilityId: number;
    RemarkId: number;
    MRNShortCode: string;
    ICENo: string;
    Income: string;
    IsInsurance: boolean;
    ReferralName: string;
    NooFVisitFree: number;
    IsAdditionalVisit: boolean;
    NewVisitFree: number;
    IsMerged: boolean;
    MergePatientId: number;
    MergeMRN: string;
    Status: number;
    Rev: number;
    CreatedBy: number;
    CreatedAt: Date;
    UpdatedBy: number;
    UpdatedAt: Date;
}

export interface PatientMergeInstance extends Instance<PatientMergeAttributes> {
    // I'm exposing every DB column as an instance field to so that tsc won't complain.
    // CreatedAt: Date;
    // UpdatedAt: Date;
    dataValues: PatientMergeAttributes;
}
