import { IAttributes } from '../../../Base/Index';
import { Instance } from '../../../../Core/Index';

export interface PatientAttributes extends IAttributes {
    [x: string]: any;
    patientdatatpl: any;
    Id: number;
    TitleId: number;
    FirstName: string;
    MiddleName: string;
    LastName: string;
    Age: number;
    DOB: Date;
    MaritalStatusId: number;
    GuardianTypeId: number;
    GuardianName: string;
    IsIvfRegistration: boolean;
    FamilyUniqueId: string;
    ReligionId: number;
    PreferredLanguageId: number;
    Qualification: string;
    NationalityId: number;
    NationalityIdentifier: string;
    PasspostNumber: string;
    VisaTypeId: number;
    VisaNumber: string;
    VisaExpiry: Date;
    IsVip: boolean;
    IsRecipient: boolean;
    IsMLC: boolean;
    MLCInfo: string;
    // PatientAssociate: string;
    CovidVaccineId: number;
    PatientTypeId: number;
    OccupationId: number;
    BloodGroupId: number;
    ReferTypeId: number;
    ReferrerId: number;
    AddressLine1: string;
    AddressLine2: string;
    Pincode: string;
    Area: string;
    City: string;
    State: string;
    Country: string;
    LandLine: string;
    Mobile: string;
    Email: string;
    // IsSmsCommunicationPreference: boolean;
    // IsEmailCommunicationPreference: boolean;
    IsMRDRequest: boolean;
    GenderId: number;
    MRN: string;
    PinCodeId: number;
    CityId: number;
    StateId: number;
    CountryId: number;
    // WardId: number;
    DistrictId: number;
    // Ward: string;
    District: string;
    AliasName: string;
    GuarantorId: number;
    RegisteredDate: Date;
    PatientStatusId: number;
    MRNTypeId: number;
    PhotoPath: string;
    IsBirthDateApproximate: boolean;
    DeathDate: Date;
    DeathTypeId: number;
    DeathPlaceId: number;
    IsDeathConfirmed: boolean;
    DeathConfirmedBy: number;
    DeathComents: string;
    DeathUpdatedBy: number;
    DeathUpdatedDate: Date;
    DeathApprovedBy: number;
    FacilityId: number;
    RemarkId: number;
    MRNShortCode: string;
    // ICENo: string;
    Income: string;
    IsInsurance: boolean;
    ReferralName: string;
    // NooFVisitFree: number;
    IsAdditionalVisit: boolean;
    NewVisitFree: number;
    IsMerged: boolean;
    MergePatientId: number;
    MergeMRN: string;
    UserId: number;
    Staff: boolean;
    IsEmergencyPatient: boolean;
    IsCorporateCustomer: boolean;
    EmergencyContactName: string;
    AlternateMobileNum: string;
    AlternateEmail: string;
    Relation: string;
    Status: number;
    Rev: number;
    CreatedBy: number;
    CreatedAt: Date;
    UpdatedBy: number;
    UpdatedAt: Date;
    DeactivatedDate: Date;
    NotificationToken: string;
    // SwosthaPatientId: number;
    ParentPatientId: number;
    CardTypeId: number;
    VipTypeId: number;
    PromotionSchemeId: number;
    CardNo: string;
    HolderName: string;
    ValidTo: Date;
    // SwosthaPatientMRN: string;
    BabyBirthTime: string;
    IsExcelUpload: boolean;
    CustomerId: number;
}

export interface PatientInstance extends Instance<PatientAttributes> {
    // I'm exposing every DB column as an instance field to so that tsc won't complain.
    // CreatedAt: Date;
    // UpdatedAt: Date;
    dataValues: PatientAttributes;
}
