import {Router, GetRouter } from '../../../Core/Index';
import Remark from './RemarkRoute';
import ResourceMaster from './ResourceMasterRoute';
import CountryMaster from './CountryMasterRoute';
import DistrictMaster from './DistrictMasterRoute';
import PatientAlert from './PatientAlertRoute';
import PincodeMaster from './PincodeMasterRoute';
import Referral from './ReferralRoute';
import ResearchProjectMember from './ResearchProjectMemberRoute';
import ResearchProject from './ResearchProjectRoute';
import StateMaster from './StateMasterRoute';
import Guarantor from './GuarantorRoute';
import GuarantorGST from './GuarantorGSTRoute';
import LocationMaster from './LocationMasterRoute';
import WardMaster from './WardMasterRoute';
import RoomTypeMaster from './RoomTypeMasterRoute';
import WardUserMap from './WardUserMapRoute';
import WardRoomMaster from './WardRoomMasterRoute';
import WardRoomBedMaster from './WardRoomBedMasterRoute';
import WardRoomServiceMap from './WardRoomServiceMapRoute';
import CityMaster from './CityMasterRoute';
import PatientAlertReview from './PatientAlertReviewRoute';
import FeedbacksMaster from './FeedbacksMasterRoute';
import GuarantorSupplementary from './GuarantorSupplimentaryRoute';
import GuarantorChecklist from './GuarantorChecklistRoute';
import ReferralCharge from './ReferralChargeRoute';
import CardMaster from './CardMasterRoute';
import GuarantorAgreement from './GuarantorAgreementRoute';
import GuarantorCardType from './GuarantorCardTypeRoute';
import GuarantorCustomer from './GuarantorCustomerRoute';
import GuarantorCustomerCard from './GuarantorCustomerCardRoute';
import GuarantorCustomerCardDeductable from './GuarantorCustomerCardDeductableRoute';
import Occupation from './OccupationRoute';
import CheckList from './CheckListRoute';
import ClinicalRemark from './ClinicalRemarkRoute';
import SystemMaster from './SystemMasterRoute';
import WardInsuranceTariff from './WardInsuranceTariffRoute';

let router: Router = GetRouter();
router.use('/Remark', Remark);
router.use('/ResourceMaster', ResourceMaster);
router.use('/CountryMaster', CountryMaster);
router.use('/DistrictMaster', DistrictMaster);
router.use('/PatientAlert', PatientAlert);
router.use('/PincodeMaster', PincodeMaster);
router.use('/Referral', Referral);
router.use('/ResearchProjectMember', ResearchProjectMember);
router.use('/ResearchProject', ResearchProject);
router.use('/StateMaster', StateMaster);
router.use('/Guarantor', Guarantor);
router.use('/GuarantorGST', GuarantorGST);
router.use('/LocationMaster', LocationMaster);
router.use('/WardMaster', WardMaster);
router.use('/RoomTypeMaster', RoomTypeMaster);
router.use('/WardUserMap', WardUserMap);
router.use('/WardRoomMaster', WardRoomMaster);
router.use('/WardRoomBedMaster', WardRoomBedMaster);
router.use('/WardRoomServiceMap', WardRoomServiceMap);
router.use('/CityMaster', CityMaster);
router.use('/PatientAlertReview', PatientAlertReview);
router.use('/FeedbacksMaster', FeedbacksMaster);
router.use('/GuarantorSupplementary', GuarantorSupplementary);
router.use('/GuarantorChecklist', GuarantorChecklist);
router.use('/ReferralCharge', ReferralCharge);
router.use('/CardMaster', CardMaster);
router.use('/GuarantorAgreement', GuarantorAgreement);
router.use('/GuarantorSupplimentary', GuarantorSupplementary);
router.use('/GuarantorCardType', GuarantorCardType);
router.use('/GuarantorCustomer', GuarantorCustomer);
router.use('/GuarantorCustomerCard', GuarantorCustomerCard);
router.use('/GuarantorCustomerCardDeductable', GuarantorCustomerCardDeductable);
router.use('/Occupation', Occupation);
router.use('/CheckList', CheckList);
router.use('/ClinicalRemark', ClinicalRemark);
router.use('/SystemMaster', SystemMaster);
router.use('/WardInsuranceTariff', WardInsuranceTariff);
export default router;
