import { Router, GetRouter } from '../../../Core/Index';
import PatientBills from './HimsPatientBillsRoute';
import PatientBillDetails from './HimsPatientBillDetailsRoute';
import PatientPaymentDetails from './HimsPatientPaymentDetailsRoute';
import PatientRefund from './HimsPatientRefundRoute';
import PatientRefundDetails from './HimsPatientRefundDetailsRoute';
import PatientBillSplitDetails from './HimsPatientBillSplitDetailsRoute';
import PatientCreditNote from './HimsPatientCreditNoteRoute';
import PatientCreditNoteDetails from './HimsPatientCreditNoteDetailsRoute';
import PatientBillSummary from './HimsPatientBillSummaryRoute';
import PatientBillLock from './HimsPatientBillLockRoute';
import PatientReturns from './HimsPatientReturnsRoute';
import PatientReturnDetails from './HimsPatientReturnDetailsRoute';
import InsurancePayment from './HimsInsurancePaymentRoute';
import InsurancePaymentDetails from './HimsInsurancePaymentDetailsRoute';
import PatientDispense from './HimsPatientDispenseRoute';
import PatientDispenseDetails from './HimsPatientDispenseDetailsRoute';
import PatientDispenseReturn from './HimsPatientDispenseReturnRoute';
import PatientDispenseReturnDetails from './HimsPatientDispenseReturnDetailsRoute';
import ClaimSubmission from './HimsClaimSubmissionRoute';
import ClaimSubmissionDetails from './HimsClaimSubmissionDetailsRoute';
import PatientInsuranceChecklist from './HimsPatientInsuranceChecklistRoute';
import PatientAccounts from './HimsPatientAccountsRoute';
import PatientPaymentAdjustments from './HimsPatientPaymentAdjustmentsRoute';
import CustomerBills from './HimsCustomerBillsRoute';
import CustomerBillDetails from './HimsCustomerBillDetailsRoute';
import UserBillingCounters from './HimsUserBillingCountersRoute';
import UserBillingCounterDenominations from './HimsUserBillingCounterDenominationsRoute';
import UserBillingCounterCancellations from './HimsUserBillingCounterCancellationsRoute';
import PatientBillPackageSummary from './HimsPatientBillPackageSummaryRoute';
import GeneralExpenses from './HimsGeneralExpensesRoute';
import OPModifyPatBills from './HimsOPModifyPatBillsRoute';
import OPModifyPatBillDetails from './HimsOPModifyPatBillDetailsRoute';
import OPModifyPatPaymentDetails from './HimsOPModifyPatPaymentDetailsRoute';
import PatientExecutableProcedure from './HimsPatientExecutableProcedureRoute';
import BankStatements from './HimsBankStatementsRoute';
import BankStatementDetails from './HimsBankStatementDetailsRoute';
import BankStatementDenominations from './HimsBankStatementDenominationsRoute';
import BankStatementCancellations from './HimsBankStatementCancellationsRoute';
import LHRCVoucher from './HimsLHRCVoucherRoute';
import LHRCVoucherDetail from './HimsLHRCVoucherDetailRoute';
import DoctorShare from './HimsDoctorShareRoute';
import DoctorShareDetails from './HimsDoctorShareDetailsRoute';
import StaffCreditPayment from './HimsStaffCreditPaymentRoute';
import StaffCreditPaymentDetails from './HimsStaffCreditPaymentDetailsRoute';
import PharmacyModifyPatBillDetails from './HimsPharmacyModifyPatBillDetailsRoute';
import PharmacyModifyPatBills from './HimsPharmacyModifyPatBillsRoute';
import PharmacyModifyPatPaymentDetails from './HimsPharmacyModifyPatPaymentDetailsRoute';
import GstReport from './HimsGstReportRoute';
import PromotionalScheme from './HimsPromotionalSchemeRoute';
import PromotionalSchemeDetail from './HimsPromotionalSchemeDetailRoute';
import PrivilegeCard from './HimsPrivilegeCardRoute';
import PrivilegeCardDetail from './HimsPrivilegeCardDetailRoute';
import PatientDoctorShareDetails from './HimsPatientDoctorShareDetailsRoute';
import CollectionBaseRevenue from './HimsCollectionBaseRevenueRoute';
import BillingRequest from './HimsBillingRequestRoute';
import DoctorShareTds from './HimsDoctorShareTdsRoute';
import ClaimCoveringletter from './HimsClaimCoveringletterRoute';
import ClaimCoveringletterDetails from './HimsClaimCoveringletterDetailsRoute';
import CollectionReport from './HimsCollectionReportRoute';
import CategoryRevenue from './CategoryRevenueRoute';
import Revenue from './RevenueRoute';
import OPStatistics from './OPStatisticsRoute';
import PosLog from './PosLogRoute';
import DynamicQRLog from './DynamicQRLogRoute';
import PosMomentLog from './PosMomentLogRoute';

let router: Router = GetRouter();
router.use('/PatientBills', PatientBills);
router.use('/PatientBillDetails', PatientBillDetails);
router.use('/PatientPaymentDetails', PatientPaymentDetails);
router.use('/PatientRefund', PatientRefund);
router.use('/PatientRefundDetails', PatientRefundDetails);
router.use('/PatientBillSplitDetails', PatientBillSplitDetails);
router.use('/PatientCreditNote', PatientCreditNote);
router.use('/PatientCreditNoteDetails', PatientCreditNoteDetails);
router.use('/PatientBillSummary', PatientBillSummary);
router.use('/PatientBillLock', PatientBillLock);
router.use('/PatientReturns', PatientReturns);
router.use('/PatientReturnDetails', PatientReturnDetails);
router.use('/InsurancePayment', InsurancePayment);
router.use('/InsurancePaymentDetails', InsurancePaymentDetails);
router.use('/PatientDispense', PatientDispense);
router.use('/PatientDispenseDetails', PatientDispenseDetails);
router.use('/PatientDispenseReturn', PatientDispenseReturn);
router.use('/PatientDispenseReturnDetails', PatientDispenseReturnDetails);
router.use('/ClaimSubmission', ClaimSubmission);
router.use('/ClaimSubmissionDetails', ClaimSubmissionDetails);
router.use('/PatientInsuranceChecklist', PatientInsuranceChecklist);
router.use('/PatientAccounts', PatientAccounts);
router.use('/PatientPaymentAdjustments', PatientPaymentAdjustments);
router.use('/CustomerBills', CustomerBills);
router.use('/CustomerBillDetails', CustomerBillDetails);
router.use('/UserBillingCounters', UserBillingCounters);
router.use('/UserBillingCounterDenominations', UserBillingCounterDenominations);
router.use('/UserBillingCounterCancellations', UserBillingCounterCancellations);
router.use('/PatientBillPackageSummary', PatientBillPackageSummary);
router.use('/GeneralExpenses', GeneralExpenses);
router.use('/OPModifyPatBills', OPModifyPatBills);
router.use('/OPModifyPatBillDetails', OPModifyPatBillDetails);
router.use('/OPModifyPatPaymentDetails', OPModifyPatPaymentDetails);
router.use('/PatientExecutableProcedure', PatientExecutableProcedure);
router.use('/BankStatements', BankStatements);
router.use('/BankStatementDetails', BankStatementDetails);
router.use('/BankStatementDenominations', BankStatementDenominations);
router.use('/BankStatementCancellations', BankStatementCancellations);
router.use('/LHRCVoucher', LHRCVoucher);
router.use('/LHRCVoucherDetail', LHRCVoucherDetail);
router.use('/DoctorShare', DoctorShare);
router.use('/DoctorShareDetails', DoctorShareDetails);
router.use('/StaffCreditPayment', StaffCreditPayment);
router.use('/StaffCreditPaymentDetails', StaffCreditPaymentDetails);
router.use('/PharmacyModifyPatBillDetails', PharmacyModifyPatBillDetails);
router.use('/PharmacyModifyPatBills', PharmacyModifyPatBills);
router.use('/PharmacyModifyPatPaymentDetails', PharmacyModifyPatPaymentDetails);
router.use('/GstReport', GstReport);
router.use('/PromotionalScheme', PromotionalScheme);
router.use('/PromotionalSchemeDetail', PromotionalSchemeDetail);
router.use('/PrivilegeCard', PrivilegeCard);
router.use('/PrivilegeCardDetail', PrivilegeCardDetail);
router.use('/PatientDoctorShareDetails', PatientDoctorShareDetails);
router.use('/CollectionBaseRevenue', CollectionBaseRevenue);
router.use('/BillingRequest', BillingRequest);
router.use('/DoctorShareTds', DoctorShareTds);
router.use('/ClaimCoveringletter', ClaimCoveringletter);
router.use('/ClaimCoveringletterDetails', ClaimCoveringletterDetails);
router.use('/CollectionReport', CollectionReport);
router.use('/CategoryRevenue', CategoryRevenue);
router.use('/Revenue', Revenue);
router.use('/OPStatistics', OPStatistics);
router.use('/PosLog', PosLog);
router.use('/DynamicQRLog', DynamicQRLog);
router.use('/PosMomentLog', PosMomentLog);

export default router;
