import { Router, GetRouter } from '../../../Core/Index';
import ItemCategory from './ItemCategoryRoute';
import ItemSubCategory from './ItemSubCategoryRoute';
import ProductType from './ProductTypeRoute';
import ProductSubType from './ProductSubTypeRoute';
import ItemMaster from './ItemMasterRoute';
import StoreMaster from './StoreMasterRoute';
import StoreMasterDetail from './StoreMasterDetailRoute';
import VendorMaster from './VendorMasterRoute';
import VendorMasterGST from './VendorMasterGSTRoute';
import UomMaster from './UomMasterRoute';
import GstMaster from './GstMasterRoute';
import PurchaseRequest from './PurchaseRequestRoute';
import PurchaseRequestDetail from './PurchaseRequestDetailRoute';
import PurchaseOrder from './PurchaseOrderRoute';
import PurchaseOrderDetail from './PurchaseOrderDetailRoute';
import Grn from './GRNRoute';
import GrnDetail from './GRNDetailRoute';
import PurchaseReturn from './PurchaseReturnRoute';
import PurchaseReturnDetail from './PurchaseReturnDetailRoute';
import StockItem from './StockItemRoute';
import StockSerialItem from './StockSerialItemRoute';
import StockMovement from './StockMovementRoute';
import StockSerialMovement from './StockSerialMovementRoute';
import StockEntry from './StockEntryRoute';
import StockEntryDetail from './StockEntryDetailRoute';
import StoreUserMap from './StoreUserMapRoute';
import StoreSetting from './StoreSettingRoute';
import StoreRack from './StoreRackRoute';
import StoreApprovalMatrix from './StoreApprovalMatrixRoute';
import StockRequest from './StockRequestRoute';
import StockRequestDetail from './StockRequestDetailRoute';
import StockTransfer from './StockTransferRoute';
import StockTransferDetail from './StockTransferDetailRoute';
import StockAdjustment from './StockAdjustmentRoute';
import StockAdjustmentDetail from './StockAdjustmentDetailRoute';
import StockConsumption from './StockConsumptionRoute';
import StockConsumptionDetail from './StockConsumptionDetailRoute';
import ThreewayMatching from './ThreewayMatchingRoute';
import ItemContractMap from './ItemContractMapRoute';
import ItemStoreMap from './ItemStoreMapRoute';
import CssdItemSetUp from './CssdItemSetUpRoute';
import CssdGroupItem from './CssdGroupItemRoute';
import UomConversion from './UomConversionRoute';
import Budget from './BudgetRoute';
import BudgetDetail from './BudgetDetailRoute';
import HsnMaster from './HsnMasterRoute';
import CustomerMaster from './CustomerMasterRoute';
import ItemFacilityMap from './ItemFacilityMapRoute';
import VendorFacilityMap from './VendorFacilityMapRoute';
import StorePreference from './StorePreferenceRoute';
import StorePreferenceMaster from './StorePreferenceMasterRoute';
import PMR from './PMRRoute';
import PMRDetail from './PMRDetailRoute';
import Indication from './IndicationRoute';
import InventoryDashboard from './InventoryDashboardRoute';
import InvWorkorder from './InvWorkorderRoute';
import InvWorkorderDetail from './InvWorkorderDetailRoute';
import ServiceBillEntry from './ServiceBillEntryRoute';
import OpticalItemMaster from './OpticalItemMasterRoute';
import OpticalStockItem from './OpticalStockItemRoute';
import OpticalStockMovement from './OpticalStockMovementRoute';
import OpticalGrn from './OpticalGrnRoute';
import OpticalGrnDetail from './OpticalGrnDetailRoute';
import StaffDiscount from './StaffDiscountRoute';
import VendorPayment from './VendorPaymentRoute';
import VendorPaymentDetails from './VendorPaymentDetailsRoute';
import ItemWantedList from './ItemWantedListRoute';
import OpticalEntry from './OpticalEntryRoute';
import Division from './DivisionRoute';
import DeviceManufacturer from './DeviceManufacturerRoute';
import Device from './DeviceRoute';
import DeviceParameters from './DeviceParametersRoute';
import InventoryAttachment from './InventoryAttachmentRoute';
import ItemSubType from './ItemSubTypeRoute';
import ReorderLevel from './ReorderLevelRoute';


let router: Router = GetRouter();
router.use('/ItemCategory', ItemCategory);
router.use('/ItemSubCategory', ItemSubCategory);
router.use('/ProductType', ProductType);
router.use('/ProductSubType', ProductSubType);
router.use('/ItemMaster', ItemMaster);
router.use('/StoreMaster', StoreMaster);
router.use('/StoreMasterDetail', StoreMasterDetail);
router.use('/VendorMaster', VendorMaster);
router.use('/VendorMasterGST', VendorMasterGST);
router.use('/UomMaster', UomMaster);
router.use('/GstMaster', GstMaster);
router.use('/PurchaseRequest', PurchaseRequest);
router.use('/PurchaseRequestDetail', PurchaseRequestDetail);
router.use('/PurchaseOrder', PurchaseOrder);
router.use('/PurchaseOrderDetail', PurchaseOrderDetail);
router.use('/Grn', Grn);
router.use('/GrnDetail', GrnDetail);
router.use('/PurchaseReturn', PurchaseReturn);
router.use('/PurchaseReturnDetail', PurchaseReturnDetail);
router.use('/StockItem', StockItem);
router.use('/StockSerialItem', StockSerialItem);
router.use('/StockMovement', StockMovement);
router.use('/StockSerialMovement', StockSerialMovement);
router.use('/StockEntry', StockEntry);
router.use('/StockEntryDetail', StockEntryDetail);
router.use('/StoreUserMap', StoreUserMap);
router.use('/StoreSetting', StoreSetting);
router.use('/StoreRack', StoreRack);
router.use('/StoreApprovalMatrix', StoreApprovalMatrix);
router.use('/StockRequest', StockRequest);
router.use('/StockRequestDetail', StockRequestDetail);
router.use('/StockTransfer', StockTransfer);
router.use('/StockTransferDetail', StockTransferDetail);
router.use('/StockAdjustment', StockAdjustment);
router.use('/StockAdjustmentDetail', StockAdjustmentDetail);
router.use('/StockConsumption', StockConsumption);
router.use('/StockConsumptionDetail', StockConsumptionDetail);
router.use('/ThreewayMatching', ThreewayMatching);
router.use('/ItemContractMap', ItemContractMap);
router.use('/ItemStoreMap', ItemStoreMap);
router.use('/CssdItemSetUp', CssdItemSetUp);
router.use('/CssdGroupItem', CssdGroupItem);
router.use('/UomConversion', UomConversion);
router.use('/Budget', Budget);
router.use('/BudgetDetail', BudgetDetail);
router.use('/HsnMaster', HsnMaster);
router.use('/CustomerMaster', CustomerMaster);
router.use('/ItemFacilityMap', ItemFacilityMap);
router.use('/VendorFacilityMap', VendorFacilityMap);
router.use('/StorePreference', StorePreference);
router.use('/StorePreferenceMaster', StorePreferenceMaster);
router.use('/PMR', PMR);
router.use('/PMRDetail', PMRDetail);
router.use('/Indication', Indication);
router.use('/InventoryDashboard', InventoryDashboard);
router.use('/InvWorkorder', InvWorkorder);
router.use('/InvWorkorderDetail', InvWorkorderDetail);
router.use('/ServiceBillEntry', ServiceBillEntry);
router.use('/OpticalItemMaster', OpticalItemMaster);
router.use('/OpticalStockItem', OpticalStockItem);
router.use('/OpticalStockMovement', OpticalStockMovement);
router.use('/OpticalGrn', OpticalGrn);
router.use('/OpticalGrnDetail', OpticalGrnDetail);
router.use('/StaffDiscount', StaffDiscount);
router.use('/VendorPayment', VendorPayment);
router.use('/VendorPaymentDetails', VendorPaymentDetails);
router.use('/ItemWantedList', ItemWantedList);
router.use('/OpticalEntry', OpticalEntry);
router.use('/Division', Division);
router.use('/DeviceManufacturer', DeviceManufacturer);
router.use('/Device', Device);
router.use('/DeviceParameters', DeviceParameters);
router.use('/InventoryAttachment', InventoryAttachment);
router.use('/ItemSubType', ItemSubType);
router.use('/ReorderLevel', ReorderLevel);
export default router;
