import {Router, GetRouter } from '../../../Core/Index';
import AllergyMaster from './AllergyMasterRoute';
import AllergyReaction from './AllergyReactionRoute';
import ChiefComplaint from './ChiefComplaintRoute';
import Diagnosis from './DiagnosisRoute';
import Procedure from './ProcedureRoute';
import ProcedureAlias from './ProcedureAliasRoute';
import ProcedureTemplate from './ProcedureTemplateRoute';
import AttachmentType from './AttachmentTypeRoute';
import GenericMaster from './GenericMasterRoute';
import Immunization from './ImmunizationRoute';
import ImmunizationSchedule from './ImmunizationScheduleRoute';
import VitalMaster from './VitalMasterRoute';
import DrugMaster from './DrugMasterRoute';
import DosageLimit from './DosageLimitRoute';
import DrugAlert from './DrugAlertRoute';
import DrugFrequency from './DrugFrequencyRoute';
import DrugFrequencyCategory from './DrugFrequencyCategoryRoute';
import TickSheet from './TickSheetRoute';
import FavoriteMaster from './FavoriteMasterRoute';
import FavoriteMasterDetail from './FavoriteMasterDetailRoute';
import TemplateMaster from './TemplateMasterRoute';
import TemplateMasterDetail from './TemplateMasterDetailRoute';
import FrequencyMaster from './FrequencyMasterRoute';
import FrequencyCategory from './FrequencyCategoryRoute';
import ServiceRateCategory from './ServiceRateCategoryRoute';
import ServiceGroup from './ServiceGroupRoute';
import ServiceCategory from './ServiceCategoryRoute';
import ServiceItem from './ServiceItemRoute';
import ServiceItemAlias from './ServiceItemAliasRoute';
import ServiceItemTariffDetail from './ServiceItemTariffDetailRoute';
import ServiceCategoryPriority from './ServiceCategoryPriorityRoute';
import ServiceItemPackageMap from './ServiceItemPackageMapRoute';
import NoteTemplate from './NoteTemplateRoute';
import ProfileSection from './ProfileSectionRoute';
import SectionMaster from './SectionMasterRoute';
import ProfileMaster from './ProfileMasterRoute';
import TickSheetMaster from './TickSheetMasterRoute';
import TickSheetMasterDetail from './TickSheetMasterDetailRoute';
import CategoryTypeMaster from './CategoryTypeMasterRoute';
import DietItemMaster from './DietItemMasterRoute';
import Category from './CategoryRoute';
import Concept from './ConceptRoute';
import Term from './TermRoute';
import IPPackage from './IPPackageRoute';
import IPPackageDetail from './IPPackageDetailRoute';
import IPPackageTariffDetail from './IPPackageTariffDetailRoute';
import IPPackageServiceInclusion from './IPPackageServiceInclusionRoute';
import IPPackageServiceExclusion from './IPPackageServiceExclusionRoute';
import Assessment from './AssessmentRoute';
import CarePath from './CarePathRoute';
import CarePathAssessment from './CarePathAssessmentRoute';
import CarePathClinicalOrder from './CarePathClinicalOrderRoute';
import CarePathPrescription from './CarePathPrescriptionRoute';
import CarePathProcedure from './CarePathProcedureRoute';
import CarePathSection from './CarePathSectionRoute';
import ProfileUser from './ProfileUserRoute';
import ChiefComplaintCategoryMap from './ChiefComplaintCategoryMapRoute';
import FitnessCertificate from './FitnessCertificateRoute';
import ABGParameters from './ABGParametersRoute';
import ClinicalFinding from './ClinicalFindingRoute';
import ImpressionMaster from './ImpressionMasterRoute';
import SystemExamination from './SystemExaminationRoute';
import ServiceItemPerformingDoctor from './ServiceItemPerformingDoctorRoute';
import ExaminationMaster from './ExaminationMasterRoute';
import DefaultNotes from './DefaultNotesRoute';

let router: Router = GetRouter();
router.use('/AllergyMaster', AllergyMaster);
router.use('/AllergyReaction', AllergyReaction);
router.use('/ChiefComplaint', ChiefComplaint);
router.use('/Diagnosis', Diagnosis);
router.use('/Procedure', Procedure);
router.use('/ProcedureAlias', ProcedureAlias);
router.use('/ProcedureTemplate', ProcedureTemplate);
router.use('/AttachmentType', AttachmentType);
router.use('/GenericMaster', GenericMaster);
router.use('/Immunization', Immunization);
router.use('/ImmunizationSchedule', ImmunizationSchedule);
router.use('/VitalMaster', VitalMaster);
router.use('/DrugMaster', DrugMaster);
router.use('/DosageLimit', DosageLimit);
router.use('/DrugAlert', DrugAlert);
router.use('/DrugFrequency', DrugFrequency);
router.use('/DrugFrequencyCategory', DrugFrequencyCategory);
router.use('/TickSheet', TickSheet);
router.use('/FavoriteMaster', FavoriteMaster);
router.use('/FavoriteMasterDetail', FavoriteMasterDetail);
router.use('/TemplateMaster', TemplateMaster);
router.use('/TemplateMasterDetail', TemplateMasterDetail);
router.use('/FrequencyMaster', FrequencyMaster);
router.use('/FrequencyCategory', FrequencyCategory);
router.use('/ServiceRateCategory', ServiceRateCategory);
router.use('/ServiceGroup', ServiceGroup);
router.use('/ServiceCategory', ServiceCategory);
router.use('/ServiceItem', ServiceItem);
router.use('/ServiceItemAlias', ServiceItemAlias);
router.use('/ServiceItemTariffDetail', ServiceItemTariffDetail);
router.use('/ServiceCategoryPriority', ServiceCategoryPriority);
router.use('/ServiceItemPackageMap', ServiceItemPackageMap);
router.use('/NoteTemplate', NoteTemplate);
router.use('/ProfileSection', ProfileSection);
router.use('/SectionMaster', SectionMaster);
router.use('/ProfileMaster', ProfileMaster);
router.use('/TickSheetMaster', TickSheetMaster);
router.use('/TickSheetMasterDetail', TickSheetMasterDetail);
router.use('/CategoryTypeMaster', CategoryTypeMaster);
router.use('/DietItemMaster', DietItemMaster);
router.use('/Category', Category);
router.use('/Concept', Concept);
router.use('/Term', Term);
router.use('/IPPackage', IPPackage);
router.use('/IPPackageDetail', IPPackageDetail);
router.use('/IPPackageTariffDetail', IPPackageTariffDetail);
router.use('/IPPackageServiceInclusion', IPPackageServiceInclusion);
router.use('/IPPackageServiceExclusion', IPPackageServiceExclusion);
router.use('/Assessment',Assessment);
router.use('/CarePath', CarePath);
router.use('/CarePathAssessment', CarePathAssessment);
router.use('/CarePathClinicalOrder', CarePathClinicalOrder);
router.use('/CarePathPrescription', CarePathPrescription);
router.use('/CarePathProcedure', CarePathProcedure);
router.use('/CarePathSection', CarePathSection);
router.use('/ProfileUser', ProfileUser);
router.use('/ChiefComplaintCategoryMap', ChiefComplaintCategoryMap);
router.use('/FitnessCertificate', FitnessCertificate);
router.use('/ABGParameters', ABGParameters);
router.use('/ClinicalFinding', ClinicalFinding);
router.use('/ImpressionMaster', ImpressionMaster);
router.use('/SystemExamination', SystemExamination);
router.use('/ServiceItemPerformingDoctor', ServiceItemPerformingDoctor);
router.use('/ExaminationMaster', ExaminationMaster);
router.use('/DefaultNotes',DefaultNotes);
export default router;
