import * as express from 'express';
import { Router, Request, Response, NextFunction } from '../../../Core/Index';
import { OptionRequest } from '../../../Common/Index';
import { BoFactory } from '../../Base/Business/Index';
import * as bo from '../../SystemSettings/Business/Index';
import * as lisbo from '../../LIS/Business/Index';
import * as regBO from '../../Registration/Business/Index';
import * as generalMasterBO from '../../GeneralMaster/Business/Index';
import * as assetManagementBO from '../../AssetManagement/Business/Index';
import * as invbo from '../../Pharmacy/Business/Index';
import * as clinicalMasterBO from '../../ClinicalMaster/Business/Index';
import * as apptBO from '../../Appointment/Business/Index';
import * as surgBO from '../../OtManagement/Business/Index';
import * as PatientEMR from '../../EMR/Business/Index';
import * as VirtualHealthcareBO from '../../VirtualHealthcare/Business/Index';
import * as billingbo from '../../Billing/Business/Index';

let router: Router = express.Router();

const OptionBoRegistry: { [key: string]: () => any } = {
    User: () => BoFactory.GetBo(bo.UserBo),
    Doctor: () => BoFactory.GetBo(bo.UserBo),
    Nurse: () => BoFactory.GetBo(bo.UserBo),
    OTTechnician: () => BoFactory.GetBo(bo.UserBo),
    Anaesthesist: () => BoFactory.GetBo(bo.UserBo),
    ApprovedUser: () => BoFactory.GetBo(bo.UserBo),
    RequestedUser: () => BoFactory.GetBo(bo.UserBo),
    AuthorizedUser: () => BoFactory.GetBo(bo.UserBo),
    CreatedUser: () => BoFactory.GetBo(bo.UserBo),
    PerformedUser: () => BoFactory.GetBo(bo.UserBo),
    ReturnedUser: () => BoFactory.GetBo(bo.UserBo),
    EnterBy: () => BoFactory.GetBo(bo.UserBo),
    Department: () => BoFactory.GetBo(bo.DepartmentBo),
    SubDepartment: () => BoFactory.GetBo(bo.DepartmentBo),
    Facility: () => BoFactory.GetBo(bo.FacilityBo),
    FromFacility: () => BoFactory.GetBo(bo.FacilityBo),
    ToFacility: () => BoFactory.GetBo(bo.FacilityBo),
    Group: () => BoFactory.GetBo(bo.GroupBo),
    Module: () => BoFactory.GetBo(bo.ModuleBo),
    Organization: () => BoFactory.GetBo(bo.OrganizationBo),
    SampleMaster: () => BoFactory.GetBo(lisbo.SampletypeBo),
    ContainterMaster: () => BoFactory.GetBo(lisbo.ContainertypeBo),
    TestMaster: () => BoFactory.GetBo(lisbo.TestmasterBo),
    TestProfile: () => BoFactory.GetBo(lisbo.TestmasterBo),
    AnalyteMaster: () => BoFactory.GetBo(lisbo.AnalytemasterBo),
    ExternalProvider: () => BoFactory.GetBo(lisbo.ExternalProviderBo),
    Role: () => BoFactory.GetBo(bo.RoleBo),
    Screen: () => BoFactory.GetBo(bo.ScreenBo),
    Speciality: () => BoFactory.GetBo(bo.SpecialityBo),
    Team: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Patient: () => BoFactory.GetBo(regBO.PatientBo),
    PatientGuarantor: () => BoFactory.GetBo(regBO.PatientGuarantorBo),
    City: () => BoFactory.GetBo(generalMasterBO.CityMasterBo),
    District: () => BoFactory.GetBo(generalMasterBO.DistrictMasterBo),
    State: () => BoFactory.GetBo(generalMasterBO.StateMasterBo),
    Country: () => BoFactory.GetBo(generalMasterBO.CountryMasterBo),
    Pincode: () => BoFactory.GetBo(generalMasterBO.PincodeMasterBo),
    Referral: () => BoFactory.GetBo(generalMasterBO.ReferralBo),
    Resource: () => BoFactory.GetBo(generalMasterBO.ResourceMasterBo),
    Remark: () => BoFactory.GetBo(generalMasterBO.RemarkBo),
    Remarks: () => BoFactory.GetBo(generalMasterBO.RemarkBo),
    Guarantor: () => BoFactory.GetBo(generalMasterBO.GuarantorBo),
    ResourceMaster: () => BoFactory.GetBo(generalMasterBO.ResourceMasterBo),
    ResearchProject: () => BoFactory.GetBo(generalMasterBO.ResearchProjectBo),
    Generic: () => BoFactory.GetBo(clinicalMasterBO.GenericMasterBo),
    Diagnosis: () => BoFactory.GetBo(clinicalMasterBO.DiagnosisBo),
    Allergy: () => BoFactory.GetBo(clinicalMasterBO.AllergyMasterBo),
    Drug: () => BoFactory.GetBo(clinicalMasterBO.DrugMasterBo),
    DietItemMaster: () => BoFactory.GetBo(clinicalMasterBO.DietItemMasterBo),
    Vital: () => BoFactory.GetBo(clinicalMasterBO.VitalMasterBo),
    ServiceGroup: () => BoFactory.GetBo(clinicalMasterBO.ServiceGroupBo),
    ServiceCategory: () => BoFactory.GetBo(clinicalMasterBO.ServiceCategoryBo),
    ServiceSubCategory: () => BoFactory.GetBo(clinicalMasterBO.ServiceCategoryBo),
    AttachmentType: () => BoFactory.GetBo(clinicalMasterBO.AttachmentTypeBo),
    NoteTemplate: () => BoFactory.GetBo(clinicalMasterBO.NoteTemplateBo),
    Profile: () => BoFactory.GetBo(clinicalMasterBO.ProfileMasterBo),
    PreDiagnosis: () => BoFactory.GetBo(clinicalMasterBO.DiagnosisBo),
    PostDiagnosis: () => BoFactory.GetBo(clinicalMasterBO.DiagnosisBo),
    ChiefComplaint: () => BoFactory.GetBo(clinicalMasterBO.ChiefComplaintBo),
    AppointmentCategory: () => BoFactory.GetBo(apptBO.AppointmentCategoryBo),
    Gender: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Title: () => BoFactory.GetBo(bo.ReferenceValueBo),
    CONTAINTYP: () => BoFactory.GetBo(bo.ReferenceValueBo),
    SAMPLETYP: () => BoFactory.GetBo(bo.ReferenceValueBo),
    VALUETYPE: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ANALYTEUOM: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ANALYTETYPE: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ANALYTEVALUETYPE: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ALIASESTYPE: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ANALYTEREFTYPE: () => BoFactory.GetBo(bo.ReferenceValueBo),
    GRAPHTYPE: () => BoFactory.GetBo(bo.ReferenceValueBo),
    COLOR: () => BoFactory.GetBo(bo.ReferenceValueBo),
    HEIGHTUNITS: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DIAMETERUNITS: () => BoFactory.GetBo(bo.ReferenceValueBo),
    LABELTYPE: () => BoFactory.GetBo(bo.ReferenceValueBo),
    STATUS: () => BoFactory.GetBo(bo.ReferenceValueBo),
    GENERICIND: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DepartmentType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    FacilityType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Language: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Qualification: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Nationality: () => BoFactory.GetBo(bo.ReferenceValueBo),
    UserCategory: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DoctorShareClass: () => BoFactory.GetBo(bo.ReferenceValueBo),
    UserGroup: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ClinicalRole: () => BoFactory.GetBo(bo.ReferenceValueBo),
    UserType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    SpecialityType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    TESTMASTERTYP: () => BoFactory.GetBo(bo.ReferenceValueBo),
    SAMPLEVOLUME: () => BoFactory.GetBo(bo.ReferenceValueBo),
    TATGROUP: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DIAGNOSISTYP: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ICDCODE: () => BoFactory.GetBo(bo.ReferenceValueBo),
    RemarkType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ResourceType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ProjectType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AlertType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Severity: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Priority: () => BoFactory.GetBo(bo.ReferenceValueBo),
    MarketingPerson: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ReferralType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    MaritalStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Religion: () => BoFactory.GetBo(bo.ReferenceValueBo),
    VipType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PatientType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    BloodGroup: () => BoFactory.GetBo(bo.ReferenceValueBo),
    VisaType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    GuardianType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ItemCategory: () => BoFactory.GetBo(invbo.ItemCategoryBo),
    ItemSubCategory: () => BoFactory.GetBo(invbo.ItemSubCategoryBo),
    ItemSubType: () => BoFactory.GetBo(invbo.ItemSubTypeBo),
    ProductType: () => BoFactory.GetBo(invbo.ProductTypeBo),
    ProductSubType: () => BoFactory.GetBo(invbo.ProductSubTypeBo),
    VendorMaster: () => BoFactory.GetBo(invbo.VendorMasterBo),
    StoreMaster: () => BoFactory.GetBo(invbo.StoreMasterBo),
    FromStore: () => BoFactory.GetBo(invbo.StoreMasterBo),
    ToStore: () => BoFactory.GetBo(invbo.StoreMasterBo),
    UomMaster: () => BoFactory.GetBo(invbo.UomMasterBo),
    GstMaster: () => BoFactory.GetBo(invbo.GstMasterBo),
    ItemMaster: () => BoFactory.GetBo(invbo.ItemMasterBo),
    TicksheetType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AllergyType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AllergyEventType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ChiefComplaintCategory: () => BoFactory.GetBo(bo.ReferenceValueBo),
    BodySite: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AllergyReactionType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DiagnosisCodeScheme: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DiagnosisVersion: () => BoFactory.GetBo(bo.ReferenceValueBo),
    CodeRegion: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ProcedureCodeScheme: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ProcedureVersion: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Equipment: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Procedure: () => BoFactory.GetBo(clinicalMasterBO.ProcedureBo),
    ProcedureType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ProcedureOperationType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ProcedureCategory: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ProcedureSubCategory: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ProcedureTemplateType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ProcedureTemplateGroup: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ProcedureTemplateCategory: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AnaesthesiaType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AllergenType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Frequency: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Period: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Condition: () => BoFactory.GetBo(clinicalMasterBO.DiagnosisBo),
    GraphType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    VitalValueType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DrugType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DrugTrade: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DrugForm: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DrugFrequency: () => BoFactory.GetBo(clinicalMasterBO.DrugFrequencyBo),
    DrugRoute: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DrugGroup: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DrugSubGroup: () => BoFactory.GetBo(bo.ReferenceValueBo),
    CategoryType: () => BoFactory.GetBo(clinicalMasterBO.CategoryTypeMasterBo),
    Category: () => BoFactory.GetBo(clinicalMasterBO.CategoryBo),
    AuthenticationLevel: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DrugAgeGroup: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DrugAlertType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AppointmentCategoryType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AppointmentSessionType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Clinic: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AppointmentSlotType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AppointmentType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AppointmentStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    VisitType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    GuarantorType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    TPA: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ServiceRateCategory: () => BoFactory.GetBo(clinicalMasterBO.ServiceRateCategoryBo),
    GuarantorClientType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    CostCenter: () => BoFactory.GetBo(bo.ReferenceValueBo),
    OrderStatus: () => BoFactory.GetBo(lisbo.OrderStatusBo),
    OrderType: () => BoFactory.GetBo(lisbo.OrderTypeBo),
    PriorityStatus: () => BoFactory.GetBo(lisbo.PriorityStatusBo),
    PatientIdentityType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    UomType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    GSTPERCENTAGE: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ScheduleType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    STORAGECONDITION: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Relationship: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ADRScore: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ActiveStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AllergySeverity: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Immunization: () => BoFactory.GetBo(clinicalMasterBO.ImmunizationBo),
    ImmunizationType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ImmunizationStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ImmunizationAdministrationType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    SocialType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    SocialFrequency: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ConditionType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ConditionStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PatientSampledetails: () => BoFactory.GetBo(lisbo.PatientSampledetailsBo),
    PatientWorkorder: () => BoFactory.GetBo(lisbo.PatientWorkorderBo),
    PatientWorkorderObservation: () => BoFactory.GetBo(lisbo.PatientWorkorderObservationBo),
    BusinessDomain: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DistributionType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PaymentTerms: () => BoFactory.GetBo(bo.ReferenceValueBo),
    CurrencyCode: () => BoFactory.GetBo(bo.ReferenceValueBo),
    VendorType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PatientStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    MRNType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DrugFrequencyType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DrugFrequencySIGCode: () => BoFactory.GetBo(bo.ReferenceValueBo),
    FrequencyCategory: () => BoFactory.GetBo(bo.ReferenceValueBo),
    TickSheetType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PrescriptionPriority: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Pharmacy: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DurationPeriod: () => BoFactory.GetBo(bo.ReferenceValueBo),
    FavoriteType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    SubstitutionAllowed: () => BoFactory.GetBo(bo.ReferenceValueBo),
    YesNo: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PanelType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ResultStatus: () => BoFactory.GetBo(lisbo.ResultStatusBo),
    WorkOrderStatus: () => BoFactory.GetBo(lisbo.WorkOrderStatusBo),
    FrequencyType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    FrequencySIGCode: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ClinicalFrequencyCategory: () => BoFactory.GetBo(bo.ReferenceValueBo),
    EncounterType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PrimaryCategory: () => BoFactory.GetBo(bo.ReferenceValueBo),
    OrderMasterStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    SourceType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    SampleUnits: () => BoFactory.GetBo(bo.ReferenceValueBo),
    CollectionSite: () => BoFactory.GetBo(bo.ReferenceValueBo),
    CollectionRoute: () => BoFactory.GetBo(bo.ReferenceValueBo),
    CollectionMethod: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PrType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PrStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AliasType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PoType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PoStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    // TemplateMaster: () => BoFactory.GetBo(clinicalMasterBO.TemplateMasterBo),
    RoomClassificationType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    WardType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Location: () => BoFactory.GetBo(generalMasterBO.LocationMasterBo),
    Block: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Ward: () => BoFactory.GetBo(generalMasterBO.WardMasterBo),
    Room: () => BoFactory.GetBo(generalMasterBO.WardRoomMasterBo),
    Bed: () => BoFactory.GetBo(generalMasterBO.WardRoomBedMasterBo),
    UserWard: () => BoFactory.GetBo(generalMasterBO.WardUserMapBo),
    DiscountType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DiscountMode: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ServiceItem: () => BoFactory.GetBo(clinicalMasterBO.ServiceItemBo),
    GrnType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    GrnSubType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    GrnStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    GrnItemType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AdmissionRequestType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AdmissionStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AdmissionType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ErpAccountType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ErpSubAccountType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ErpGLClassType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Bank: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ContactType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ReceiptType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    RefundType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    StockEntryType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    StockEntryStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PaymentType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    StorePrivillages: () => BoFactory.GetBo(bo.ReferenceValueBo),
    StoreType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    StoreSubType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    StorePolicy: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ReceiptStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    RefundStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Payments: () => BoFactory.GetBo(bo.ReferenceValueBo),
    VendorItem: () => BoFactory.GetBo(invbo.ItemVendorMapBo),
    Rank: () => BoFactory.GetBo(bo.ReferenceValueBo),
    CurrencyType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PatientBillStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    BillPriority: () => BoFactory.GetBo(bo.ReferenceValueBo),
    CardType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    BillType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    SurgeryType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    RequestType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    StockRequestType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    RequestStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    StockRequestStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    StockPriority: () => BoFactory.GetBo(bo.ReferenceValueBo),
    NoteType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    UserStores: () => BoFactory.GetBo(invbo.StoreUserMapBo),
    StoreItem: () => BoFactory.GetBo(invbo.ItemStoreMapBo),
    TransactionType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ProcedureName: () => BoFactory.GetBo(clinicalMasterBO.ProcedureBo),
    AdjustmentType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AdjustmentStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ConsumptionType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ConsumptionStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    RequestedStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    TransferType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    TransferStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Terminal: () => BoFactory.GetBo(bo.ReferenceValueBo),
    CreditNoteType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DoctorInvoiceStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Assessment: () => BoFactory.GetBo(clinicalMasterBO.AssessmentBo),
    SectionMaster: () => BoFactory.GetBo(clinicalMasterBO.SectionMasterBo),
    RoomTypeMaster: () => BoFactory.GetBo(generalMasterBO.RoomTypeMasterBo),
    EscortUser: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Control: () => BoFactory.GetBo(bo.ControlBo),
    OTRegisterStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    OTRequestStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    OTRoom: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AssetType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AssetCategory: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Manufacturer: () => BoFactory.GetBo(bo.ReferenceValueBo),
    WarrantyStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    FreeStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AMCStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    CMCStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ServiceRequestStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    WOStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AssignType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    WarrantyType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DietType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DietPreferrence: () => BoFactory.GetBo(bo.ReferenceValueBo),
    FoodPreferrence: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DietItemType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DietCategory: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DietFrequency: () => BoFactory.GetBo(bo.ReferenceValueBo),
    TherapeuticDiet: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PatientDietPlanStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    FeedbackCategory: () => BoFactory.GetBo(bo.ReferenceValueBo),
    FeedbackType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Rating: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Feedbacks: () => BoFactory.GetBo(generalMasterBO.FeedbacksMasterBo),
    Description: () => BoFactory.GetBo(generalMasterBO.FeedbacksMasterBo),
    MLCStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PatientFeedbackStatus: () => BoFactory.GetBo(generalMasterBO.FeedbacksMasterBo),
    PrivateDueApprover: () => BoFactory.GetBo(bo.UserBo),
    DiscountApprover: () => BoFactory.GetBo(bo.UserBo),
    LockType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    LockStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Prnbtn: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PrnStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ReturnStore: () => BoFactory.GetBo(invbo.StoreMasterBo),
    PatientDietNbmType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PatientDietNbmStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PharmacySaleType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ModeOfDelivery: () => BoFactory.GetBo(bo.ReferenceValueBo),
    LabourStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    CongentialAnomalies: () => BoFactory.GetBo(bo.ReferenceValueBo),
    JellyCordCutBy: () => BoFactory.GetBo(bo.ReferenceValueBo),
    JellyCordType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Stools: () => BoFactory.GetBo(bo.ReferenceValueBo),
    RhFactor: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PatencyOfAnus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Urine: () => BoFactory.GetBo(bo.ReferenceValueBo),
    BirthOutCome: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Respiration: () => BoFactory.GetBo(bo.ReferenceValueBo),
    MuscleTone: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Reflexes: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Colour: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DeliveryComplications: () => BoFactory.GetBo(bo.ReferenceValueBo),
    CordBloodFor: () => BoFactory.GetBo(bo.ReferenceValueBo),
    LabourGender: () => BoFactory.GetBo(bo.ReferenceValueBo),
    NewBornStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    GABy: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Labour: () => BoFactory.GetBo(bo.ReferenceValueBo),
    MembraneRuptured: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AmnoticFluid: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Presentation: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Indication: () => BoFactory.GetBo(bo.ReferenceValueBo),
    GrossAppearance: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PostPartumCondition: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Medication: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Assistant: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PlacentaMembranes: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Episiotomy: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Laceration: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Rack: () => BoFactory.GetBo(invbo.StoreRackBo),
    WorklistStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PrnType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PatientReturnStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    FacilityPreference: () => BoFactory.GetBo(bo.FacilityPreferenceBo),
    EventSource: () => BoFactory.GetBo(bo.ReferenceValueBo),
    EventStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    EventType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    EventDataType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    EventDestination: () => BoFactory.GetBo(bo.ReferenceValueBo),
    EventDirection: () => BoFactory.GetBo(invbo.StoreRackBo),
    EntityType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ARCollection: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Revenue: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AccountPayable: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Inventory: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Merge: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ERPMasters: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PatientRequestPriority: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PatientReturnPriority: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PatientRequestStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AssessmentType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PatientRequestType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    WashingType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    WashingMachineType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    CleaningType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PackingType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Tray: () => BoFactory.GetBo(bo.ReferenceValueBo),
    CleaningMachineType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    TempType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    HighTemperature: () => BoFactory.GetBo(bo.ReferenceValueBo),
    LowTemperature: () => BoFactory.GetBo(bo.ReferenceValueBo),
    MovedToStore: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ColourIndication: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DoctorPaymentStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    CarePathType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ReturnReason: () => BoFactory.GetBo(bo.ReferenceValueBo),
    EmployeeAttachmentType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    CarePath: () => BoFactory.GetBo(clinicalMasterBO.CarePathBo),
    StockReturnType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    TranferedUser: () => BoFactory.GetBo(bo.UserBo),
    PharmacyReturnType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Coordinator: () => BoFactory.GetBo(bo.UserBo),
    TrainingPaymentType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    FamilyLink: () => BoFactory.GetBo(regBO.FamilyLinkBo),
    RequesitionStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    CandidateStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    PrinterOption: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DispensedUser: () => BoFactory.GetBo(bo.UserBo),
    CardName: () => BoFactory.GetBo(generalMasterBO.CardMasterBo),
    AssetName: () => BoFactory.GetBo(assetManagementBO.AssetBo),
    AnalyzerTestName: () => BoFactory.GetBo(lisbo.AnalyzerTestBo),
    PMRCategory: () => BoFactory.GetBo(bo.ReferenceValueBo),
    BillingCounterStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    BillingCounter: () => BoFactory.GetBo(bo.ReferenceValueBo),
    Denomination: () => BoFactory.GetBo(bo.ReferenceValueBo),
    SectionNoteType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    SequenceOption: () => BoFactory.GetBo(bo.ReferenceValueBo),
    TravelStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    TravelType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    SupplyType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    UserTechnicians: () => BoFactory.GetBo(bo.UserBo),
    LabIncharge: () => BoFactory.GetBo(bo.UserBo),
    RadiologyIncharge: () => BoFactory.GetBo(bo.UserBo),
    LabTechnician: () => BoFactory.GetBo(bo.UserBo),
    RadiologyTechnician: () => BoFactory.GetBo(bo.UserBo),
    Impression: () => BoFactory.GetBo(clinicalMasterBO.ImpressionMasterBo),
    ClinicalFindings: () => BoFactory.GetBo(clinicalMasterBO.ClinicalFindingBo),
    TreatedUser: () => BoFactory.GetBo(bo.UserBo),
    ReferedUser: () => BoFactory.GetBo(bo.UserBo),
    CheckLists: () => BoFactory.GetBo(generalMasterBO.CheckListBo),
    ReferralStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    CustomerType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    GuarantorCardType: () => BoFactory.GetBo(generalMasterBO.GuarantorCardTypeBo),
    GuarantorCustomer: () => BoFactory.GetBo(generalMasterBO.GuarantorCustomerBo),
    EndoscopyIncharge: () => BoFactory.GetBo(bo.UserBo),
    OrgIsolation: () => BoFactory.GetBo(lisbo.OrgIsolationBo),
    Instruments: () => BoFactory.GetBo(clinicalMasterBO.ServiceItemBo),
    ProcedureTests: () => BoFactory.GetBo(clinicalMasterBO.ServiceItemBo),
    MRDFileType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AssetDepartment: () => BoFactory.GetBo(bo.DepartmentBo),
    AssetUser: () => BoFactory.GetBo(bo.UserBo),
    ClinicalRemarks: () => BoFactory.GetBo(generalMasterBO.ClinicalRemarkBo),
    EyeDiagnosis: () => BoFactory.GetBo(clinicalMasterBO.DiagnosisBo),
    SystemMasters: () => BoFactory.GetBo(generalMasterBO.SystemMasterBo),
    ExaminationSystem: () => BoFactory.GetBo(generalMasterBO.SystemMasterBo),
    LaserAdvice: () => BoFactory.GetBo(generalMasterBO.SystemMasterBo),
    SurgeryAdvice: () => BoFactory.GetBo(generalMasterBO.SystemMasterBo),
    InjectionAdvice: () => BoFactory.GetBo(generalMasterBO.SystemMasterBo),
    MRDDepartment: () => BoFactory.GetBo(bo.DepartmentBo),
    OtRooms: () => BoFactory.GetBo(generalMasterBO.WardRoomMasterBo),
    B2BCustomerMaster: () => BoFactory.GetBo(lisbo.B2BCustomerMasterBo),
    DoctorClass: () => BoFactory.GetBo(bo.ReferenceValueBo),
    ShareType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    OpticalGrnType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    OpticalGrnStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    StaffDiscountType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    BloodBankDepartment: () => BoFactory.GetBo(bo.DepartmentBo),
    Staff: () => BoFactory.GetBo(bo.UserBo),
    CVS: () => BoFactory.GetBo(clinicalMasterBO.SystemExaminationBo),
    RS: () => BoFactory.GetBo(clinicalMasterBO.SystemExaminationBo),
    Abdomen: () => BoFactory.GetBo(clinicalMasterBO.SystemExaminationBo),
    CNS: () => BoFactory.GetBo(clinicalMasterBO.SystemExaminationBo),
    FitForDonating: () => BoFactory.GetBo(clinicalMasterBO.SystemExaminationBo),
    Rejected: () => BoFactory.GetBo(clinicalMasterBO.SystemExaminationBo),
    PerformingDoctor: () => BoFactory.GetBo(clinicalMasterBO.ServiceItemPerformingDoctorBo),
    SurgeryRoomType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    SurgeryRoom: () => BoFactory.GetBo(surgBO.SurgeryRoomMasterBo),
    TemplateMaster: () => BoFactory.GetBo(clinicalMasterBO.TemplateMasterBo),
    TreatementModality: () => BoFactory.GetBo(PatientEMR.TreatementModalityBo),
    ExaminationMaster: () => BoFactory.GetBo(clinicalMasterBO.ExaminationMasterBo),
    EscortType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    AccidentType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    VirtualCategory: () => BoFactory.GetBo(VirtualHealthcareBO.VirtualCategoryBo),
    VirtualSubCategory: () => BoFactory.GetBo(VirtualHealthcareBO.VirtualSubCategoryBo),
    PromotionalScheme: () => BoFactory.GetBo(billingbo.PromotionalSchemeBo),
    Division: () => BoFactory.GetBo(invbo.DivisionBo),
    BillingRequestType: () => BoFactory.GetBo(bo.ReferenceValueBo),
    BillingRequestStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    CancelReqRaisedStatus: () => BoFactory.GetBo(bo.ReferenceValueBo),
    CategorySubId: () => BoFactory.GetBo(bo.ReferenceValueBo),
    DeviceManufacturer: () => BoFactory.GetBo(invbo.DeviceManufacturerBo),
    PMR: () => BoFactory.GetBo(invbo.PMRBo),
};

router.post('/GetOptions', (req: Request, res: Response, next: NextFunction): any => {
    let promises: Array<any> = [];
    let reqs = req.body as Array<OptionRequest>;
    reqs.forEach(r => {
        let func = OptionBoRegistry[r.Key];
        if (func) {
            let bo = func();
            bo.Request = req;
            if (bo.GetOptions) {
                let p = bo.GetOptions(r.Key, r.Request || { Params: [] })
                    .then((response: any) => {
                        if (r.Default === undefined || r.Default === true) {
                            (<any[]>response[r.Key]).splice(0, 0, { Id: -1, Text: 'Please Select', ReferenceValueCode: -1 });
                        }
                        if (typeof r.Default === 'object') {
                            (<any[]>response[r.Key]).splice(0, 0, r.Default);
                        }
                        return response;
                    });
                promises.push(p);
            } else {
                next(new Error('GetOptions method is not implemented'));
            }
        } else {
            let refBO = BoFactory.GetBo(bo.ReferenceValueBo, req) as any;
            let p = refBO.GetOptions(r.Key, r.Request || { Params: [] })
                .then((response: any) => {
                    if (r.Default === undefined || r.Default === true) {
                        (<any[]>response[r.Key]).splice(0, 0, { Id: -1, Text: 'Please Select', ReferenceValueCode: -1, Color: '' });
                    }
                    if (typeof r.Default === 'object') {
                        (<any[]>response[r.Key]).splice(0, 0, r.Default);
                    }
                    return response;
                });
            promises.push(p);
        }
    });
    Promise.all(promises)
        .then(response => {
            let r = {};
            for (let i of response) {
                for (let j in i) {
                    (<any>r)[j] = (<any>i)[j];
                }
            }
            res.send(r);
        })
        .catch(err => next(err));
});

export default router;
