import { Router, GetRouter } from '../../../Core/Index';
import AdmissionRequest from './AdmissionRequestRoute';
import BedHousekeeping from './BedHousekeepingRoute';
import BedTransportation from './BedTransportationRoute';
import BedTransfer from './BedTransferRoute';
import BedOccupancyHistory from './BedOccupancyHistoryRoute';
import Bedtransportationlog from './BedtransportationlogRoute';
import BedHousekeepinglog from './BedHousekeepinglogRoute';
import PatientAdmissionLog from './PatientAdmissionLogRoute';
import PatientAdmissionRequestLog from './PatientAdmissionRequestLogRoute';
import PatientStockRequests from './PatientStockRequestsRoute';
import PatientStockRequestDetails from './PatientStockRequestDetailsRoute';
import PatientDischargeEvent from './PatientDischargeEventRoute';
import BedReservationDetail from './BedReservationDetailRoute';
import FileRequest from './FileRequestRoute';
import FileIssue from './FileIssueRoute';
import PatientStockReturns from './PatientStockReturnsRoute';
import PatientStockReturnDetails from './PatientStockReturnDetailsRoute';
import MRDLocation from './MRDLocationRoute';
import MRDMovement from './MRDMovementRoute';
import MRDFileAttachments from './MRDFileAttachmentsRoute';
import DietDashboard from './DietDashboardRoute';
import MRDFiles from './MRDFilesRoute';
import IPFileRequest from './IPFileRequestRoute';
import PatientSickLeaveForm from './PatientSickLeaveFormRoute';
import IPClearence from './IPClearenceRoute';

let router: Router = GetRouter();
router.use('/AdmissionRequest', AdmissionRequest);
router.use('/BedHousekeeping', BedHousekeeping);
router.use('/BedTransportation', BedTransportation);
router.use('/BedTransfer', BedTransfer);
router.use('/BedOccupancyHistory', BedOccupancyHistory);
router.use('/Bedtransportationlog', Bedtransportationlog);
router.use('/BedHousekeepinglog', BedHousekeepinglog);
router.use('/PatientAdmissionLog', PatientAdmissionLog);
router.use('/PatientAdmissionRequestLog', PatientAdmissionRequestLog);
router.use('/PatientStockRequests', PatientStockRequests);
router.use('/PatientStockRequestDetails', PatientStockRequestDetails);
router.use('/PatientDischargeEvent', PatientDischargeEvent);
router.use('/BedReservationDetail', BedReservationDetail);
router.use('/FileRequest', FileRequest);
router.use('/FileIssue', FileIssue);
router.use('/PatientStockReturns', PatientStockReturns);
router.use('/PatientStockReturnDetails', PatientStockReturnDetails);
router.use('/MRDLocation', MRDLocation);
router.use('/MRDMovement', MRDMovement);
router.use('/MRDFileAttachments', MRDFileAttachments);
router.use('/DietDashboard', DietDashboard);
router.use('/MRDFiles', MRDFiles);
router.use('/IPFileRequest', IPFileRequest);
router.use('/PatientSickLeaveForm', PatientSickLeaveForm);
router.use('/IPClearence', IPClearence);
export default router;
