import { IAttributes } from '../../../Base/Index';
import { Instance } from '../../../../Core/Index';

export interface FacilityAttributes extends IAttributes {
    Id: number;
    OrganizationId: number;
    FacilityCode: string;
    FacilityName: string;
    FacilityTypeId: number;
    Description: string;
    AddressLine1: string;
    AddressLine2: string;
    PinCode: string;
    Area: string;
    City: string;
    State: string;
    Country: string;
    LandLine: string;
    Mobile: string;
    FaxNo: string;
    Email: string;
    LanguageId: number;
    ActiveFrom: Date;
    ActiveTo: Date;
    IsPurchaseReturnEditable: boolean;
    IsGstRegistered: boolean;
    GstNumber: string;
    RegistrationNo: string;
    TaxActiveFrom: Date;
    TaxActiveTo: Date;
    LicenseExpiryDate: Date;
    PinCodeId: number;
    CityId: number;
    StateId: number;
    CountryId: number;
    WardId: number;
    DistrictId: number;
    Ward: string;
    District: string;
    PAN: string;
    TAXPlayerUserName: string;
    TAXPlayerPassword: string;
    IsDeptWiseLabPrint: boolean;
    FacilityLogo: Text;
    LogoPath: string;
    SecondLogoPath: string;
    IsShowItemType: boolean;
    IsActive: boolean;
    IsLabCentre: boolean;
    IsMedicineCentre: boolean;
    IsVAT: boolean;
    IsConvertionQtyEdit: boolean;
    IsAddressSearch: boolean;
    IsDoctorShare: boolean;
    IsAdmissionDate: boolean;
    // IsPatientSearchbyEnter: boolean;
    IsCashPatientEmrIndent: boolean;
    ActiveStatusId: number;
    Lat: number;
    Lng: number;
    ResultFormatTypeId: number;
    MaxRescheduleTime: number;
    IsSwosthaIntegration: boolean;
    IsMultipleDiscount: boolean;
    IsItemmasterDrugshow: boolean;
    IsAlternateEmailMandatory: boolean;
    IsAlternateMobileMandatory: boolean;
    IsDueBill: boolean;
    SwosthaURI: string;
    SwosthaKey: string;
    SeniorCitizenDiscount: number;
    Status: number;
    Rev: number;
    CreatedBy: number;
    CreatedAt: Date;
    UpdatedBy: number;
    UpdatedAt: Date;
    IsPincodeFreeText: boolean;
    IsWardRoomEditable: boolean;
    IsItemCodeEdit: boolean;
    ShowAliasInfo: boolean;
    ShowMrp: boolean;
    MrpPercent: string;
    HouseKeepingNumber: string;
}

export interface FacilityInstance extends Instance<FacilityAttributes> {
    // I'm exposing every DB column as an instance field to so that tsc won't complain.
    // CreatedAt: Date;
    // UpdatedAt: Date;
    dataValues: FacilityAttributes;
}
