import { IAttributes } from '../../../Base/Index';
import { Instance } from '../../../../Core/Index';

export interface UserAttributes extends IAttributes {
    Id: number;
    TitleId: number;
    FirstName: string;
    MiddleName: string;
    LastName: string;
    Age: number;
    DOB: Date;
    PreferredLanguageId: number;
    Qualification: string;
    NationalityId: number;
    CategoryId: number;
    DoctorShareClassId: number;
    ActionFrom: Date;
    ActionTo: Date;
    AddressLine1: string;
    AddressLine2: string;
    Pincode: string;
    Area: string;
    City: string;
    District: string;
    State: string;
    Country: string;
    LandLine: string;
    Mobile: string;
    Email: string;
    Experience: string;
    PANNo: string;
    AccountNo: string;
    IFSCCode: string;
    BankName: string;
    AdditionalPhoneNo: string;
    LicenseNo: string;
    Designation: string;
    LicenseIssueDate: Date;
    LicenseExpiryDate: Date;
    IsAdmittingConsultant: boolean;
    IsVisistingConsultant: boolean;
    IsSurgeon: boolean;
    OrgId: number;
    FacilityId: number;
    VirtualCategoryId: number;
    VirtualSubCategoryId: number;
    DepartmentId: number;
    SubDepartmentId: number;
    UserGroupId: number;
    ClinicalRoleId: number;
    UserTypeId: number;
    SpecialityId: number;
    Image: string;
    Signature: string;
    UserName: string;
    Password: string;
    SecurityPin: string;
    TabletAccess: boolean;
    MobileAccess: boolean;
    LoginPermission: boolean;
    BillingCounterId: number;
    BillingCounterStatusId: number;
    GenderId: number;
    PhotoPath: string;
    SignPath: string;
    IsActive: boolean;
    IsHome: boolean;
    ActiveStatusId: number;
    PatientId: number;
    PinCodeId: number;
    OPDRoomId: number;
    CityId: number;
    DistrictId: number;
    StateId: number;
    CountryId: number;
    Status: number;
    Rev: number;
    CreatedBy: number;
    CreatedAt: Date;
    UpdatedBy: number;
    UpdatedAt: Date;
    PrivateDueLimit: number;
    DiscountLimit: number;
    DiscountModeId: number;
    IsPrivate: boolean;
    IsDefaultPrivateDue: boolean;
    IsPharmacyDueAllowed: boolean;
    IsDiscount: boolean;
    IsTDS: boolean;
    TDSId: number;
    Staff: boolean;
    BillAmount: number;
    PaidAmount: number;
    OutStandingAmount: number;
    IsPatientPortalDoctor: boolean;
    IsPeadiatrician: boolean;
    IsAnaesthisist: boolean;
    EmployeeId: number;
    QmsLocationId: number;
    PrescriptionAdvice: string;
    DoctorClassId: number;
    IsIncludeTax: boolean;
    IsVirtualUsers: boolean;
    IsDueCheck: boolean;
    NotificationToken: string;
    TeamId: number;
    AadharNumber: string;
    IsExcelUpload: boolean;
}

export interface UserInstance extends Instance<UserAttributes> {
    // I'm exposing every DB column as an instance field to so that tsc won't complain.
    // CreatedAt: Date;
    // UpdatedAt: Date;
    dataValues: UserAttributes;
}
