import { IAttributes } from '../../../Base/Index';
import { Instance } from '../../../../Core/Index';

export interface PatientOrderDetailAttributes extends IAttributes {
    Id: number;
    PatientOrderId: number;
    DisplaySeqId: number;
    PatientId: number;
    GroupId: number;
    RequestDate: Date;
    TestId: number;
    TestCode: string;
    TestName: string;
    CategoryName: string;
    TestDescription: string;
    TestTypeId: number;
    SideId: number;
    TestMasterPositionId: number;
    DiagnosisId: number;
    TestPrice: number;
    TestPriceCurrencyCode: string;
    TestPriceCode: string;
    Discount: number;
    TestCost: number;
    TestCostCurrencyCode: string;
    TestCostCode: string;
    TaxId: number;
    TaxCost: number;
    IsOrdered: number;
    DoctorId: number;
    DoctorName: string;
    OrderToLocationId: number;
    OrderLocationId: number;
    OrderStatusId: number;
    OrderPriorityId: number;
    TestInstruction: string;
    SpecimanId: number;
    BodySiteId: number;
    GuarantorId: number;
    IsAlertRequired: number;
    IsProcessed: number;
    RepeatFrequency: string;
    Indication: string;
    IsUsePreviousSample: boolean;
    Reason: string;
    Extoid: string;
    ProfileName: string;
    PackageName: string;
    MasterObjectTypeId: number;
    MasterId: number;
    DepartmentId: number;
    SubDepartmentId: number;
    Quantity: number;
    ScheduleDate: Date;
    ResultEstimatedDate: Date;
    IsCanceled: number;
    CanceledById: number;
    CanceledDateTime: Date;
    PrimaryInsId: number;
    SecondaryInsId: number;
    ReferrarShare: number;
    IsCalculateGST: number;
    NetAmount: number;
    PatientBillDetailId: number;
    PatientBillId: number;
    PatientBillStatusId: number;
    IsPackage: boolean;
    IsDirectBill: boolean;
    IsExecutableProcedure: boolean;
    ExternalProviderId: number;
    ExternalProviderCost: number;
    IsAdditionalVisit: boolean;
    DoctorClassId: number;
    PerformDoctorId: number;
    PerformDrShare: number;
    DoctorShare: number;
    EligiblePercentage: number;
    SharePercentage: number;
    ShareAmount: number;
    DrShareTaxId: number;
    DrTaxPercentage: number;
    DrTaxAmount: number;
    ClinicalReason: string;
    OrderComments: string;
    IsExternalLab: boolean;
    ExternalPrice: number;
    InsNetAmount: number;
    PatNetAmount: number;
    ClinicalData: string;
    Duration: string;
    DurationPeriodId: number;
    IsFollowup: boolean;
    Status: number;
    Rev: number;
    CreatedBy: number;
    CreatedAt: Date;
    UpdatedBy: number;
    UpdatedAt: Date;
}

export interface PatientOrderDetailInstance extends Instance<PatientOrderDetailAttributes> {
    // I'm exposing every DB column as an instance field to so that tsc won't complain.
    // CreatedAt: Date;
    // UpdatedAt: Date;
    dataValues: PatientOrderDetailAttributes;
}
