import { IAttributes } from '../../../Base/Index';
import { Instance } from '../../../../Core/Index';

export interface PatientOrderAttributes extends IAttributes {
    Id: number;
    EncounterId: number;
    PatientId: number;
    OrderTypeId: number;
    IsDirectBill: boolean;
    ConsultationId: number;
    OrderNumber: string;
    OrderRequestDate: Date;
    OrderScheduleDate: Date;
    DoctorId: number;
    DoctorName: string;
    OrderFromId: number;
    OrderToId: number;
    SubDepartmentId: number;
    OrderStatusId: number;
    OrderCompletedDate: Date;
    OrderPriorityId: number;
    OrderTotal: number;
    ParentDeparementId: number;
    OrderToLocation: number;
    OrderLocationId: number;
    PatientMRN: string;
    AccessionNumber: string;
    ExternalLabId: number;
    HisOrderId: string;
    SourceTypeId: number;
    ReferredId: number;
    ReferredBy: string;
    OrderNotes: string;
    OrderComments: string;
    BillingStatusId: number;
    PatientBillStatusId: number;
    OrderPackageId: number;
    OrderPackageName: number;
    BillingId: number;
    BillNumber: string;
    BillAmount: number;
    BillDate: Date;
    ResultEstimateDate: Date;
    GroupId: number;
    Reason: string;
    Extoid: string;
    DataTemplateId: number;
    InstanceIdentifier: string;
    BillTypeId: number;
    PrimaryInsId: number;
    SecondaryInsId: number;
    ScheduledDate: Date;
    OrderAuthorizedById: number;
    OrderAuthorizeByName: string;
    OrderAuthorizedDate: Date;
    BedId: number;
    WardId: number;
    RoomId: number;
    TestTypeId: number;
    PatientBillId: number;
    ServiceRateCategoryId: number;
    EncounterTypeId: number;
    ReviewStatusId: number;
    IsAdditionalVisit: boolean;
    PatientReceiptId: number;
    Status: number;
    Rev: number;
    CreatedBy: number;
    CreatedAt: Date;
    UpdatedBy: number;
    UpdatedAt: Date;
    FacilityId: number;
    PatientName: string;
    PatientMobile: string;
    SurgeryIdentifier: string;
    SurgeryEntryId: number;
    IsVirtualOrders: boolean;
    IsLabOrders: boolean;
    IsVaccineOrders: boolean;
    // ParentPatientId: number;
    VirtualOrderId: number;
    SubCategoryId: number;
    Address: string;
    Landmark: string;
    StartTime: string;
    EndTime: string;
    PaymentGatewayRefNo: string;
    PaymentModeId: number;
    Amount: number;
    PaymentStatusId: number;
    BankName: string;
    ApprovalNumber: string;
    ResultFormatTypeId: number;
    IsPaidFully: boolean;
    IsBooking: boolean;
    IsGovtApproved: boolean;
    IsGovtCancelled: boolean;
    IsOxygenOrders: boolean;
    NoofDays: number;
    MinAdvance: number;
    CancelReason: string;
    RenewalId: number;
    IsRenewed: boolean;
    IsExternalLab: boolean;
    LISId: number;
    LISResultId: number;
    ExternalOrderStatusId: number;
    NetPatientAmount: number;
    NetInsuranceAmount: number;
}

export interface PatientOrderInstance extends Instance<PatientOrderAttributes> {
    // I'm exposing every DB column as an instance field to so that tsc won't complain.
    // CreatedAt: Date;
    // UpdatedAt: Date;
    dataValues: PatientOrderAttributes;
}
