import { Router, GetRouter } from '../../../Core/Index';
import User from './UserRoute';
import Organization from './OrganizationRoute';
import Facility from './FacilityRoute';
import Department from './DepartmentRoute';
import Speciality from './SpecialityRoute';
import ReferenceValueGroup from './ReferenceValueGroupRoute';
import ReferenceValue from './ReferenceValueRoute';
import DepartmentLocation from './DepartmentLocationRoute';
import Group from './GroupRoute';
import Role from './RoleRoute';
import UserDefinedField from './UserDefinedFieldRoute';
import Module from './ModuleRoute';
import Screen from './ScreenRoute';
import UserTeam from './UserTeamRoute';
import Team from './TeamRoute';
import UserTaxDetail from './UserTaxDetailRoute';
import FacilityDefaultService from './FacilityDefaultServiceRoute';
import Control from './ControlRoute';
import FacilitySetting from './FacilitySettingRoute';
import AppInfo from './AppInfoRoute';
import Context from './ContextRoute';
import FacilityPreference from './FacilityPreferenceRoute';
import BillingSetting from './BillingSettingRoute';
import FacilityDashboard from './FacilityDashboardRoute';
import FacilityPreferenceMaster from './FacilityPreferenceMasterRoute';
import UserPreference from './UserPreferenceRoute';
import EventDashboard from './EventDashboardRoute';
import RolePrivilege from './RolePrivilegeRoute';
import ERPIntegration from './ERPIntegrationRoute';
import LoginSession from './LoginSessionRoute';
import MasterExport from './MasterExportRoute';
import EventTemplate from './EventTemplateRoute';
import CronStatusRoute from './CronStatusRoute';
import UserDefaultService from './UserDefaultServiceRoute';
import UserCategoryMap from './UserCategoryMapRoute';
import RoleMobileConfigMap from './RoleMobileConfigMapRoute';
import Message from './MessageRoute';
import OtpVerify from './OtpVerifyRoute';
import UserFacilityMap from './UserFacilityMapRoute';

let router: Router = GetRouter();
router.use('/User', User);
router.use('/Organization', Organization);
router.use('/Facility', Facility);
router.use('/Department', Department);
router.use('/Speciality', Speciality);
router.use('/ReferenceValueGroup', ReferenceValueGroup);
router.use('/ReferenceValue', ReferenceValue);
router.use('/DepartmentLocation', DepartmentLocation);
router.use('/Group', Group);
router.use('/Role', Role);
router.use('/UserDefinedField', UserDefinedField);
router.use('/Module', Module);
router.use('/Screen', Screen);
router.use('/UserTeam', UserTeam);
router.use('/Team', Team);
router.use('/UserTaxDetail', UserTaxDetail);
router.use('/FacilityDefaultService', FacilityDefaultService);
router.use('/Control', Control);
router.use('/FacilitySetting', FacilitySetting);
router.use('/AppInfo', AppInfo);
router.use('/Context', Context);
router.use('/FacilityPreference', FacilityPreference);
router.use('/BillingSetting', BillingSetting);
router.use('/FacilityDashboard', FacilityDashboard);
router.use('/FacilityPreferenceMaster', FacilityPreferenceMaster);
router.use('/UserPreference', UserPreference);
router.use('/EventDashboard', EventDashboard);
router.use('/RolePrivilege', RolePrivilege);
router.use('/ERPIntegration', ERPIntegration);
router.use('/LoginSession', LoginSession);
router.use('/MasterExport', MasterExport);
router.use('/EventTemplate', EventTemplate);
router.use('/CronStatusRoute', CronStatusRoute);
router.use('/UserDefaultService', UserDefaultService);
router.use('/UserCategoryMap', UserCategoryMap);
router.use('/RoleMobileConfigMap', RoleMobileConfigMap);
router.use('/Message', Message);
router.use('/OtpVerify',OtpVerify);
router.use('/UserFacilityMap',UserFacilityMap);
export default router;
