import { Router, GetRouter } from '../../../Core/Index';
import Containertype from './ContainertypeRoute';
import Sampletype from './SampletypeRoute';
import Analytemaster from './AnalytemasterRoute';
import Testmaster from './TestmasterRoute';
import Ticksheetmaster from './TicksheetmasterRoute';
import Externalproviders from './ExternalprovidersRoute';
import InvestigationSettings from './InvestigationSettingsRoute';
import OrderStatus from './OrderStatusRoute';
import OrderType from './OrderTypeRoute';
import PriorityStatus from './PriorityStatusRoute';
import PatientWorkorderObservation from './PatientWorkorderObservationRoute';
import PatientWorkorder from './PatientWorkorderRoute';
import PatientWorkorderdetails from './PatientWorkorderdetailsRoute';
import Drawsite from './DrawsiteRoute';
import PatientSampledetails from './PatientSampledetailsRoute';
import WorkOrderStatus from './WorkOrderStatusRoute';
import ResultStatus from './ResultStatusRoute';
import PatientOrderStatus from './PatientOrderStatusRoute';
import WorkOrderSample from './WorkOrderSampleRoute';
import WorkOrderSampleDetail from './WorkOrderSampleDetailRoute';
import ExternalProvider from './ExternalProviderRoute';
import PriceMapping from './PriceMappingRoute';
import WorkOrderAttachment from './WorkOrderAttachmentRoute';
import WorkOrderObservation from './WorkOrderObservationRoute';
import LABDashboard from './LABDashboardRoute';
import OrderTAT from './OrderTATRoute';
import AnalyzerTest from './AnalyzerTestRoute';
import AnalyzerAnalyteMap from './AnalyzerAnalyteMapRoute';
import AnalyserTemplate from './AnalyserTemplateRoute';
import LISInterface from './LISInterfaceRoute';
import LISInterfaceResults from './LISInterfaceResultsRoute';
import LISInterfacePatientDetails from './LISInterfacePatientDetailsRoute';
import AntibioticMaster from './AntibioticMasterRoute';
import PatientWorkOrderAntibiotics from './PatientWorkOrderAntibioticsRoute';
import OrgIsolation from './OrgIsolationRoute';
import B2BCustomerMaster from './B2BCustomerMasterRoute';
import PatientCriticalOrder from './PatientCriticalOrderRoute';
import RISInterfaceResult from './RISInterfaceResultRoute';

let router: Router = GetRouter();
router.use('/Containertype', Containertype);
router.use('/Sampletype', Sampletype);
router.use('/Analytemaster', Analytemaster);
router.use('/Testmaster', Testmaster);
router.use('/Ticksheetmaster', Ticksheetmaster);
router.use('/Externalproviders', Externalproviders);
router.use('/InvestigationSettings', InvestigationSettings);
router.use('/OrderStatus', OrderStatus);
router.use('/OrderType', OrderType);
router.use('/PriorityStatus', PriorityStatus);
router.use('/PatientWorkorderObservation', PatientWorkorderObservation);
router.use('/PatientWorkorder', PatientWorkorder);
router.use('/PatientWorkorderdetails', PatientWorkorderdetails);
router.use('/Drawsite', Drawsite);
router.use('/PatientSampledetails', PatientSampledetails);
router.use('/WorkOrderStatus', WorkOrderStatus);
router.use('/ResultStatus', ResultStatus);
router.use('/PatientOrderStatus', PatientOrderStatus);
router.use('/WorkOrderSample', WorkOrderSample);
router.use('/WorkOrderSampleDetail', WorkOrderSampleDetail);
router.use('/ExternalProvider', ExternalProvider);
router.use('/PriceMapping', PriceMapping);
router.use('/WorkOrderAttachment', WorkOrderAttachment);
router.use('/WorkOrderObservation', WorkOrderObservation);
router.use('/LABDashboard', LABDashboard);
router.use('/OrderTAT', OrderTAT);
router.use('/AnalyzerTest', AnalyzerTest);
router.use('/AnalyzerAnalyteMap', AnalyzerAnalyteMap);
router.use('/AnalyserTemplate', AnalyserTemplate);
router.use('/LISInterface', LISInterface);
router.use('/LISInterfaceResults', LISInterfaceResults);
router.use('/LISInterfacePatientDetails', LISInterfacePatientDetails);
router.use('/AntibioticMaster', AntibioticMaster);
router.use('/PatientWorkOrderAntibiotics', PatientWorkOrderAntibiotics);
router.use('/OrgIsolation', OrgIsolation);
router.use('/B2BCustomerMaster', B2BCustomerMaster);
router.use('/PatientCriticalOrder', PatientCriticalOrder);
router.use('/RISInterfaceResult', RISInterfaceResult);

export default router;
